Size ratio to sptite
aranion/game_andromeda pull request #15
Opened 2022-11-02 10:57 UTC by Melekh11

### Добавить пропорции среза у Sprite

теперь можно изменять размер спрайтов на экране не меняя размеров spritesheet

2022-11-02 11:19 UTC, elaineir commented
Привет! Мне нельзя ревьюить, поэтому призываю @HereHaveTheseFlowers

2022-11-03 16:37 UTC, elaineir requested changes
А ты проверял код? Для игрока делаю `sizeRatio = 2`, выставляю точные размеры jодного кадра спрайта (68), получаю такую картинку:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/75016726/199780155-3fa3aafe-e10b-48e4-8aad-cd6642b148f1.gif)

2022-11-03 16:37 UTC, elaineir commented on packages/client/src/pages/Game/core/entities/sprite/index.ts
> +  private sizeRatio: number;
```suggestion
  private readonly sizeRatio: number;
```
Можно добавить, чтобы случайно не перезаписать где-нибудь в методах

2022-11-04 11:00 UTC, elaineir commented
> теперь можно изменять размер спрайтов на экране не меняя размеров spritesheet

Вообще система спрайтов заточена именно под точный размер одного кадра, и он может быть не всегда квадратным. Поэтому данная реализация увеличения спрайта здесь не очень уместна. К тому же у нас нет ~~художника~~ какой-то константы одной ячейки для спрайтового грида, и обрезать по мультипликаторам смысла нет.

Если ты видишь практическую пользу от этого, то поясни, пожалуйста. Желательно с конкретным примером.

Если увеличивать спрайт на экране, то тут нужно обратить внимание именно на _скалирование_ по осям X Y, а не срез. Но вместе со скалированием нужно будет править позиционирование объекта на экране и его радиус коллизий.

2022-11-04 22:22 UTC, Melekh11 commented
привет, код проверял
предположим, изначальный размер спрайта на spritesheet'е - 34
если нужно сделать корабль в 2 раза больше, то нужно выставить размер спрайта - 68 и sizeRatio =  0.5 (тк срез по холсту будет 68*0.5 = его размер на холсте)

да, изначально у меня было желание просто увеличить спрайт, если это будет нужно.
на моей практике я столкнулся с тем что я находил слишком большие спрайты для астероидов, которые приходилось уменьшать в редакторах. Может в будущем я всегда буду находить spritesheet'ы подходящие по размерам, но хочется иметь возможность решить эту проблему при необходимости.

Сейчас картинка может быть и прямоугольной и квадратной. Спрайт может иметь любые пропорции, он просто умножается на какой-то коэффициент. Потери функциональности нет. Твой вариант тоже можно реализовать, но мне он кажется сложнее.

2022-11-04 23:57 UTC, elaineir commented
> если нужно сделать корабль в 2 раза больше, то нужно выставить размер спрайта - 68 и sizeRatio = 0.5 (тк срез по холсту будет 68*0.5 = его размер на холсте)

Ок, смотри, это неочевидное поведение, и тогда нужно это обозначать в комментариях, чтобы было понятно, не залезая в код. Используя мультипликатор 2 ожидаешь, что спрайт будет больше в два раза, а не наоборот.

Также сейчас мультипликатор не пересчитывает изначальные значения, переданные в класс, то есть это по сути уже не мультипликатор, и надо вручную высчитывать все оставшиеся значения отображения: радиус, ширину и высоту.

Попробуй улучшить api так, чтобы при sizeRatio > 1 спрайт визуально увеличивался с пересчетом сопутствующих параметров. А при sizeRatio < 1 уменьшался.

То есть ситуация из работы. Я передаю в статы:
```
radius: 34,
```
Мой самолетик рисуется как есть. Хочу увеличить его ещё в 2 раза. Все, что мне нужно сделать, это передать дополнительно `sizeRatio: 2`, ничего больше не меняя. Его поведение на канвасе при этом не должно сломаться.
Потом мне не понравился его размер, ведь прошлый был самое то, и я хочу просто удалить `sizeRatio: 2`, не пересчитывая ему радиус и прочие свойства.

2022-11-09 19:50 UTC, Melekh11 commented
со всем согласен и всё поправил!
поведение на канвасе не ломается, для изменения размеров спрайта достаточно только указать / изменить `sizeRatio`

2022-11-14 10:55 UTC, elaineir commented
Задача продублирована в https://github.com/aranion/game_andromeda/pull/25

2022-11-14 16:45 UTC, closed without merging