Feature/AND-73 Астероиды
aranion/game_andromeda pull request #16
Opened 2022-11-02 18:54 UTC by Melekh11

### Добавляем астероиды

в одном из четырёх углов карты спавнятся астероиды с рандомной скоростью и направлением движения
при соприкосновении с игроком отнимают ему жизнь и пропадают
при вылете за экран удаляются

2022-11-03 16:02 UTC, elaineir requested changes
Наши задачи пересекаются, так что провела ревью.
В целом хорошо, но надо будет поправить замечания.

2022-11-03 16:02 UTC, elaineir commented on packages/client/src/pages/Game/core/entities/asteroid/animations.ts
> +export const asteroidAnimations: Pick<AnimationType, 'asteroid'> = {
Учитывая, что в спрайтах кадр только один, то лучше не писать анимацию астероиду, а просто с конфигом прокинуть `isAnimated: false` в самом классе астероида. Так спрайт будет вырезаться по координатам [0, 0].

2022-11-03 16:02 UTC, elaineir commented on packages/client/src/pages/Game/core/entities/asteroid/index.ts
> +    super(config);
```suggestion
    super({ ...config, isAnimated: false );
```
Вот так. Анимации и `currentAnimation` для астероида можно будет везде удалить

2022-11-03 16:02 UTC, elaineir commented on packages/client/src/pages/Game/core/entities/asteroid/stats.ts
> +export function createAsteroid(): Omit<
Судя по названию, функция должна возвращать объект астероида, а не конфиг.

Стоит поменять название функции или возвращать уже готовый объект.

2022-11-03 16:02 UTC, elaineir commented on packages/client/src/pages/Game/core/entities/asteroid/stats.ts
> +    imageSrc: img, // todo: реализовать выбор рандомного астероида
Возможно, стоит сразу реализовать рандомайзер скинов?

Можно собрать их в массив и случайно выбирать по индексу. Тогда можно будет убрать и условную конструкцию в коде выше.

У меня в ветке с ресурсами есть функция `randomInteger`, могла бы тут пригодиться

2022-11-03 16:02 UTC, elaineir commented on packages/client/src/pages/Game/core/overworld/game-map/index.ts
> +            x:
Возможно астероиду стоит самому определять свое местоположение. Другой логики для него все равно не подразумевается. И зависимость здесь только от размеров канваса, который он может взять из конфига.

2022-11-03 16:02 UTC, elaineir commented on packages/client/src/pages/Game/core/overworld/game-map/index.ts
> +        i--;
В цикле `forEach` данная операция не имеет смысла, этот цикл идет последовательно и манипулировать порядком перебора нельзя.
В моей песочнице этот код был закомментирован, и тут сначала был цикл `for` (в котором как раз можно менять порядок перебора).
`i--` нужно, чтобы исправить баг с мерцанием при удалении одного из объектов из массива. С циклом forEach  это мерцание остается.

В общем, тут нужен цикл `for` вместо `forEach`

2022-11-03 16:02 UTC, elaineir commented on packages/client/src/pages/Game/core/overworld/game-map/index.ts
> +        asteroid &&
Здесь условия будут пересекаться с условиями для ресурсов, я вынесла его в отдельный метод `isCollided`

2022-11-03 16:02 UTC, elaineir commented on packages/client/src/pages/Game/core/overworld/game-map/index.ts
> +  public handleAsteroids({ frame = 0 }: UpdateParams) {
В кач-ве параметра можно использовать просто `frame` как примитив, вряд ли тут будут ещё какие-то параметры

2022-11-03 16:02 UTC, elaineir commented on packages/client/src/pages/Game/core/overworld/game-map/types.ts
> +export type handleResourcesParams = UpdateParams & {
Нужно удалить, этот тип относится к ресурсам, которые вне этой задачи

2022-11-03 16:02 UTC, elaineir commented on packages/client/src/pages/Game/core/entities/asteroid/index.ts
> +  draw() {
Лучше написать ключ `protected`, чтобы никто внешний не смог вызвать метод

2022-11-04 23:12 UTC, Melekh11 commented on packages/client/src/pages/Game/core/entities/asteroid/animations.ts
> +export const asteroidAnimations: Pick<AnimationType, 'asteroid'> = {
да! так куда лучше

2022-11-04 23:22 UTC, Melekh11 commented on packages/client/src/pages/Game/core/overworld/game-map/index.ts
> +            x:
Да! Так и `game-map` чище

2022-11-04 23:42 UTC, Melekh11 commented on packages/client/src/pages/Game/core/overworld/game-map/index.ts
> +        i--;
да, раньше не замечал мерцания
другое возможное решение проблемы: делать `setTimeout(() => {...}, 0)`

2022-11-04 23:54 UTC, Melekh11 commented on packages/client/src/pages/Game/core/entities/asteroid/stats.ts
> +    imageSrc: img, // todo: реализовать выбор рандомного астероида
ой! просмотрел
да, `randomInteger` помог!

2022-11-05 00:21 UTC, Melekh11 commented
спасибо за ревью!
код стал чище и читабельней

2022-11-07 08:36 UTC, elaineir commented on packages/client/src/pages/Game/core/overworld/game-map/index.ts
> +        i--;
`setTimeout` с нулевой задержкой это почти всегда костыль, а не решение. Если код можно выполнить синхронно, то лучше добиться правильного поведения, не прибегая к подобным трюкам.

2022-11-07 08:53 UTC, elaineir requested changes

2022-11-07 08:53 UTC, elaineir commented on packages/client/src/pages/Game/core/overworld/game-map/index.ts
> +    this.asteroids.forEach((asteroid, i) => {
Поменяй цикл на `for`, нам не нужны костыли.
setTimeout нужно удалить

2022-11-08 22:15 UTC, Melekh11 commented
добавил `for` , но баг остался (появляется при столкновении на большой скорости)

2022-11-09 04:53 UTC, elaineir commented
У меня ещё был баг, когда астероид появлялся не из-за границ канваса, а просто появлялся, как при телепорте -- тоже на высокой скорости. Может не стоило делать ему такую высокую скорость, канвас не успевает отрисовать.

2022-11-09 04:58 UTC, elaineir approved these changes

2022-11-09 08:39 UTC, practicum-maxim-zyryanov approved these changes

2022-11-09 09:20 UTC, merged