feature/AND-22 FORUM
aranion/game_andromeda pull request #22
Opened 2022-11-07 09:01 UTC by EkaHvo

### Разработка страниц форума

2022-11-07 11:30 UTC, HereHaveTheseFlowers commented
Бесит, что vercel не дает перейти на '/forum' 😠 😠 😠 
А посмотреть на страничку очень хочется! Можешь скрины прикрепить? Или ПР еще WIP?

2022-11-07 12:10 UTC, EkaHvo commented
![Andromeda-forum](https://user-images.githubusercontent.com/69339749/200307068-dd53deeb-24a9-4ba2-9861-06a5059d5774.jpg)
![Andromeda-topic](https://user-images.githubusercontent.com/69339749/200307070-de2ea4ec-ad45-4cce-89fe-5c1dc5568e00.jpg)
![Andromeda-forumModal](https://user-images.githubusercontent.com/69339749/200307071-95b03096-5f97-4394-a112-36d928e3b97b.jpg)
![Andromeda-forum586](https://user-images.githubusercontent.com/69339749/200307073-fb76aefa-ff2f-4d9e-b799-54f2f2532d2b.jpg)
![Andromeda-topics586](https://user-images.githubusercontent.com/69339749/200307076-69f7fbd7-4df9-4ce2-b8a3-f754bd701d5d.jpg)
![Andromeda-topic586](https://user-images.githubusercontent.com/69339749/200307077-054029f1-0654-4162-82b4-1dfa86e0635e.jpg)
![Andromeda-modal586](https://user-images.githubusercontent.com/69339749/200307079-99d6371a-7139-4c56-8c2e-c35db42b4898.jpg)

2022-11-08 08:23 UTC, aranion commented on packages/client/src/components/Card/index.tsx
> +  const { className, children, id } = props;
тут передаются в 
`Props = React.HTMLAttributes<HTMLElement>; `
если id не используется для вычислений, его можно не вытаскивать и передать все что было передано в пропсы :
`const { className, children, ...othetProps} = props;` 
и в div полностью передать все, что пришло : 
` <div {...othetProps} className={classNames} >
      {children}
  </div>`

Тут получается, мы вытащили className и children и ВСЕ, что осталось, передали параметрами в div.

2022-11-08 08:26 UTC, aranion commented on packages/client/src/components/Card/index.tsx
> +type CardProps = React.HTMLAttributes<HTMLElement>;
имхо, если `CardProps` не экспортируется, зачем его идентифицировать?) Можно же просто `Props` .
Это просто мысли.

2022-11-08 08:32 UTC, aranion commented on packages/client/src/components/Modal/index.tsx
> +import { FC } from 'react';
На код не влияет, но лучше указывать, что это type : `import type { FC } from 'react';`
Сам все время забываю

2022-11-08 08:34 UTC, aranion commented on packages/client/src/components/Modal/index.tsx
> +interface ModalProps extends Props {
можно заменить на такую конструкцию: 
`type Props = React.HTMLAttributes<HTMLElement> & {active: boolean; setActive: any;`

2022-11-08 08:37 UTC, aranion commented on packages/client/src/components/Modal/index.tsx
> +  setActive: any;
setActive скорее всего функция, лучше  any за на `setActive: (isActive: boolean) => void;`

2022-11-08 08:50 UTC, aranion commented on packages/client/src/components/Modal/index.tsx
> +        {title ? <div className='modal__title'>{title}</div> : ''}
Если идет отрисовка компонента, от условия, лучше возвращать не `''`, а `null`.
Также в данном случае лучше заменить на конструкцию:
`{title && <div className='modal__title'>{title}</div> }`
При необходимости можно рассмотреть вариант использования оператора `??` (https://mariusschulz.com/blog/nullish-coalescing-the-operator-in-typescript)

2022-11-08 08:52 UTC, aranion commented on packages/client/src/components/Modal/index.tsx
> +        className={classnames('modal__content', { active: active })}
`{ active: active })}` можно `{ active})}`

2022-11-08 08:59 UTC, aranion commented on packages/client/src/components/Modal/index.tsx
> +      onClick={() => setActive(false)}>
ссылочные типы в пропсах - плохо.
![image](https://user-images.githubusercontent.com/71134155/200519780-9f11c88f-6d2e-4810-b759-6a6baf17ee98.png)
Работать будет, но лучше по возможности вынести в отдельную функцию:
`const handleActive = () => {setActive(false)}` и в компоненте: `onClick={handleActive}`

2022-11-08 09:03 UTC, aranion commented on packages/client/src/components/Modal/index.tsx
> +        onClick={e => e.stopPropagation()}>
Тут тоже лучше вынести стрелочную функцию:
`const handleClick = (e: React.MouseEvent<HTMLDivElement, MouseEvent>) => {
    e.stopPropagation()
  }` и `onClick={handleClick}`

2022-11-08 09:08 UTC, aranion commented on packages/client/src/components/Modal/styles.css
> +  left: 0;
возможно лишние top и left
![image](https://user-images.githubusercontent.com/71134155/200522622-f47e6839-8823-4d89-8b56-24aae5f09643.png)

2022-11-08 09:11 UTC, aranion commented on packages/client/src/components/Modal/styles.css
> +  color: #ffffca;
`background-color: #372948;` и `color: #ffffca;` лучше заменить на css переменные из файла `constants/_vars.css`: 
`background-color: var(--color-normal);` и `color: var(--color-light);`

2022-11-08 09:13 UTC, aranion commented on packages/client/src/components/Table/index.tsx
> +  return <table className='table'>{children}</table>;
Сомнительная польза компонента) Сможешь пояснить зачем он тут?

2022-11-08 09:14 UTC, aranion commented on packages/client/src/components/Table/styles.css
> +  color: #ffffca;
тоже лучше взять из переменных `var(--...)`

2022-11-08 09:20 UTC, aranion commented on packages/client/src/components/Table/styles.css
> +td {
`th` `td` если ты не вкладываешь их в выше стоящий компонент, данные стили будут применимы ко всем `th` `td` в проекте, что скажется перезаписью стилей..
Нужно или дать уникальные имена, например `.myTable__th` и `.myTable__td` и их уже присваивать в таблице. Или указать, что они вложены `.table th` и `.table td` - этот вариант хуже, но в целом лучше чем просто указать `th` `td`

2022-11-08 09:22 UTC, aranion commented on packages/client/src/components/Textarea/index.tsx
> +  const { placeholder, onChange, className, value } = props;
как писал выше, тут лишний код, можно: 
`const { className, ...otherProps} = props;`
и
`<textarea {...otherProps} className={classNames}/>`

2022-11-08 09:25 UTC, aranion commented on packages/client/src/components/Textarea/styles.css
> +  font-weight: 400;
font-style: normal;
font-weight: 400;
значения по умолчанию, если на них не действует другие стили, смысла в них нет.

2022-11-08 09:25 UTC, aranion commented on packages/client/src/components/Textarea/styles.css
> +  border: 0;
border: none;

2022-11-08 09:28 UTC, aranion commented on packages/client/src/components/Textarea/styles.css
> +.textarea:focus::placeholder {
и вообще, если я правильно понял тут стили дублируют стили из Input, возможно стоит доработать компонент <Input />.
Например использования переделанного компонента  `<Input type='textarea' />` или `<Input type='input' />`
Это на бедующее, сейчас просто стили дублируются по коду.

2022-11-08 09:31 UTC, aranion commented on packages/client/src/index.css
> +.forum {
стили для `forum` но они объявлены глобально? Есть проблемы чтобы их поместить в сам компонент?

2022-11-08 09:38 UTC, aranion commented on packages/client/src/store/forum/types.ts
> +  topicId?: string;
если все элементы необязательные можно обернуть все в Partial:
`export type TopicProps = Partial<{
  topicId: string;
  title: string;
  author: string;
  description: string;
  content: string;
  commentCount: string;
}>;`
подробнее про полезные функции TS https://www.typescriptlang.org/docs/handbook/utility-types.html

2022-11-08 09:41 UTC, aranion requested changes
Привет! Все хорошо, но думаю стоит кое что подправить. Если возникнут вопросы по комментариям, пиши.

2022-11-08 09:43 UTC, aranion commented on packages/client/src/pages/Forum/index.tsx
> +      <Button className='button__back' onClick={() => navigate(-1)}>
Отлично что есть кнопка назад, Есть смысл ее вынести в отдельный компонент и использовать ее по всему проекту.

2022-11-08 09:46 UTC, aranion commented on packages/client/src/pages/Forum/index.tsx
> +          {forums.map((forum: ForumProps) => (
нет смысла типизировать forum. Нужно типизировать forums:
`const forums: ForumProps[] = [];` и тогда `forums.map((forum)` forum сам определит тип

2022-11-08 09:48 UTC, aranion commented on packages/client/src/pages/Forum/index.tsx
> +              key={forum.forumId}
Стоит применить lеструктуризацию const {forumId, title, topicsCount, commentsCount } = forum, код будет выгладить чище

2022-11-08 09:50 UTC, aranion commented on packages/client/src/pages/ForumItem/index.tsx
> +import { NewTopicButton } from '../../components/Forum/NewTopicButton';
import { TopicItem } from '../../components/Forum/TopicItem';
import { NewTopicButton } from '../../components/Forum/NewTopicButton';
Возможно не прописан импорт в `component/index.ts` должно быть импорт:
`import { Button, Table, TopicItem, NewTopicButton   } from '../../components';`

2022-11-08 10:01 UTC, aranion commented on packages/client/src/pages/Topic/index.tsx
> +        <div className='topic__title'>{topic?.title}</div>
`{topic?.title}` тут может появиться div у которого внутри будет написано undefined.
Как вариант `{topic?.title || ''}`

2022-11-08 10:06 UTC, aranion commented on packages/client/src/components/Form/index.tsx
> +  const { onSubmit, className, children, title } = props;
можно переделать ...otherProps, выше писал

2022-11-08 10:11 UTC, aranion commented on packages/client/src/components/Form/styles.css
> +  height: 30px;
высоту input и button возможно стоит не указывать явно, а использовать pading, сейчас изменение размера шрифта не сможет автоматически подстроиться высота.

2022-11-08 10:15 UTC, aranion commented on packages/client/src/components/Forum/ForumItem/index.tsx
> +        <Link to={`/forum/${forumId}`}>
дублирование кода, и изменение роутинга(RouterList) влечет к поломке всех мест где было написан путь руками:
`<Link to={`${RouterList.FORUM}/${forumId}`}>`

2022-11-08 10:23 UTC, aranion commented on packages/client/src/components/Forum/NewCommentButton/index.tsx
> +import { Form } from '../../Form';
import { Button, Modal, Textarea, Star } from '../..';
import { Form } from '../../Form';
к
import { Button, Modal, Textarea, Star, Form  } from '../..';

2022-11-08 10:26 UTC, aranion commented on packages/client/src/components/Forum/NewCommentButton/index.tsx
> +          children={'New Comment'}
Ну можно и так)) но children подразумевает: 
`<Button className='button_center' onClick={handleOpen} > New Comment </Button>`

2022-11-08 10:27 UTC, aranion commented on packages/client/src/components/Forum/NewCommentButton/index.tsx
> +  const [madalActive, setModalActive] = useState(false);
логические переменные лучше начинать с is `isMadalActive`

2022-11-08 10:31 UTC, aranion commented on packages/client/src/components/Forum/TopicItem/index.tsx
> +        <Link to={`/topic/${topicId}`}>
через RouterList

2022-11-08 10:53 UTC, aranion commented on packages/client/src/components/Forum/NewCommentButton/index.tsx
> +          onClick={handleOpen}
Если компонент используется совместно с form, то стоит передавать тип `submit` вместо onClick, а на форму уже ставить обработчик onSubmit

2022-11-09 07:36 UTC, EkaHvo commented on packages/client/src/components/Modal/index.tsx
> +        {title ? <div className='modal__title'>{title}</div> : ''}
правлю на {title ? <div className='modal__title'>{title}</div> : null} Мне кажется так более декларативно

2022-11-09 07:39 UTC, EkaHvo commented on packages/client/src/components/Modal/styles.css
> +  left: 0;
Тут у меня почему-то не показывает дублирование стилей (открывала в хроме и лисе). если убираю - начинает уезжать ovelay

2022-11-09 07:40 UTC, EkaHvo commented on packages/client/src/components/Table/index.tsx
> +  return <table className='table'>{children}</table>;
Тут была задумка допилить полноценную таблицу, но что-то пошло не по плану) Удалила

2022-11-09 07:40 UTC, EkaHvo commented on packages/client/src/components/Textarea/styles.css
> +.textarea:focus::placeholder {
Поправила, надо поставить задачку на попозже слить их с инпутом

2022-11-09 07:41 UTC, EkaHvo commented on packages/client/src/index.css
> +.forum {
перекинула в компонент

2022-11-09 07:42 UTC, EkaHvo commented on packages/client/src/pages/Forum/index.tsx
> +      <Button className='button__back' onClick={() => navigate(-1)}>
Вынесла с отдельный компонент эту кнопку и кнопку со звездами для форума.

2022-11-09 07:56 UTC, EkaHvo commented on packages/client/src/components/Forum/NewCommentButton/index.tsx
> +          onClick={handleOpen}
тут кнопка открытия модалки)

2022-11-09 09:09 UTC, aranion commented on packages/client/src/components/Modal/index.tsx
> +        {title ? <div className='modal__title'>{title}</div> : ''}
Не принципиально, просто дополнительный код. 
Если title === 0 или '', div не отрисуется вообще, если так и должно быть, то все ок

2022-11-09 09:11 UTC, aranion commented on packages/client/src/components/Modal/styles.css
> +  left: 0;
Ок, если нужен, то оставляй)

2022-11-09 09:17 UTC, aranion commented on packages/client/src/components/Forum/NewCommentButton/index.tsx
> +          onClick={handleOpen}
ок)

2022-11-09 09:21 UTC, aranion commented on packages/client/src/components/ButtonBack/index.tsx
> +    <Button className='button__back' onClick={backNavigate}>
(имхо) БЭМ. Лучше просто `className='button'`

2022-11-09 09:29 UTC, aranion commented on packages/client/src/components/Forum/ForumButton/index.tsx
> +    <div className='forum__button'>
(имхо) БЭМ. <div className='forum__button'> подразумевает выше стоящий <div className='forum'>, лучше переименовать <div className='button'> или <div className='forum-button'> или <div className='forumButton'>. 
И чтобы стили не пересекались с другими стилями в проект, стоит использовать styles.module.css

2022-11-09 09:31 UTC, aranion commented on packages/client/src/components/Forum/ForumButton/index.tsx
> +      <Button className='button_center' onClick={onClick}>
(имхо) БЭМ. как вариант ` <Button className='forumButton__center' onClick={onClick}>`

2022-11-09 09:33 UTC, aranion commented on packages/client/src/components/Forum/ForumItem/index.tsx
> +import { RouterList } from '../../../router/routerList';
после последних изменинй в проекте, добавились алиас src. Если не сложно, можно все заменить на ` import { RouterList } from 'src/router/routerList';` , `import { ForumProps } from 'src/store/forum/types';`

2022-11-09 09:35 UTC, aranion commented on packages/client/src/components/Forum/NewCommentButton/index.tsx
>  import { FetchComments } from '../../../store/forum/types';
`import type { FetchComments } from 'src/store/forum/types';`

2022-11-09 09:36 UTC, aranion commented on packages/client/src/components/Forum/NewCommentButton/index.tsx
> +  const [isModalActive, setModalActive] = useState(false);
`setModalActive` ==> `setIsModalActive`

2022-11-09 09:37 UTC, aranion commented on packages/client/src/components/Forum/NewForumButton/index.tsx
>    const [description, setContent] = useState('');
`const [description, setContent] = useState('');`
к
` const [description, setDescription] = useState('');`

2022-11-09 09:48 UTC, aranion commented on packages/client/src/components/index.ts
> +export * from './Forum/TopicItem';
так..)) тут что-то пошло не так.
нужно добавить в `src/component/Forum/index.ts`
в котором указать все компоненты которые оттуда экспортируются:
`export * from './TopicItem';
export * from './NewTopicButton';
export * from './ForumItem';
export * from './NewForumButton';
export * from './Comment';
export * from './NewCommentButton';
export * from './ForumButton';`

и уже в `src/components/index.ts` указать просто `export * from './Forum';`

2022-11-09 09:50 UTC, aranion commented on packages/client/src/pages/Forum/index.tsx
> +import { ButtonBack, Star, ForumItem, NewForumButton } from '../../components';
теперь можно import { ButtonBack, Star, ForumItem, NewForumButton } from 'src/components';

2022-11-09 09:55 UTC, aranion approved these changes
Все хорошо, комментарии которые оставил носят информационный характер, можно скорректировать перед заливкой в develop

2022-11-10 11:55 UTC, practicum-maxim-zyryanov approved these changes
После исправления по комментариям коллег, код стал заметно лучше - это аппрув. Единственно вставлю своё замечание в контексте реальных проектов.

2022-11-10 11:55 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/Topic/index.tsx
> +  };
Здесь хорошо, что предзаданные данные сокрыты за методом, а вся остальная логика написана с позиции того, что работает как бы с реальным методом. Тем не менее, когда возникнет необходимость переходить с мокированного метода на реальный, потребуется вносить изменения в файл, при внесении изменений есть небольшой шанс задеть логику, но куда важнее, что в крупных проектах может внесение подобного изменения потребует пересборки проекта. Сейчас это не проблема, даю аппрув, но в будущем рекомендовал бы выносить предзаданные данные в файл, к которому обращаться через реальный метод получения по URL, тогда для перехода с предзаданных данных на API достаточно заменить URL, который в свою очередь может подгружаться как настойка приложения при запуске, а следовательно не потребует манипуляций с кодом и пересборки.

2022-11-10 11:55 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/ForumItem/index.tsx
> +  };
Аналогичная ситуация

2022-11-10 11:55 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/Forum/index.tsx
> +  };
Аналогичная ситуация

2022-11-10 12:02 UTC, merged