feature/AND-76
aranion/game_andromeda pull request #25
Opened 2022-11-11 21:38 UTC by Melekh11

### добавляем класс Particle (+ Particles)

Particle - отвечает за отрисовку одной частицы
Particles - следит за изменением прозрачности группы частиц, собирает мусор

2022-11-11 21:38 UTC, Melekh11 commented
### Particle vs GameObject
Particle во многом похож на GameObject, однако реализацию последнего менять не стал
Стоит ли это делать ради DRY - вопрос.

2022-11-14 10:41 UTC, elaineir requested changes
В ПР выполнены 3 задачи: 76 (Particle), 82 (увеличение спрайта) и 86 (фон из звезд). Напоминаю, что 1 Пр = 1 задача.

Весь код к 86 задаче нужно удалить, 76 и 82 вольем, но другой ПР тогда нужно закрыть.

Particle относится к визуальным эффектам, его лучше отнести в папку `overworld`, но точно не отдельно от всех. Лучше ещё поделить на отдельные папки `particle` и `particles`, а сами файлы назвать `index.ts`/

Также в ПР есть неиспользуемый спрайт, его тоже нужно удалить.

2022-11-14 10:41 UTC, elaineir commented on packages/client/src/pages/Game/core/particle/particle.ts
> +  normalizePosition(canvasSize: Coordinates) {
Есть ощущение, что за этим должен следить слой над `Particle`, так как этот класс только рендерит частицу, а за ее положение в пространстве отвечает слой выше.

Попробуй переместить этот метод в класс `Particles`.
А классу частицы добавить сеттер на `position`

2022-11-14 10:41 UTC, elaineir commented on packages/client/src/pages/Game/core/particle/particles.ts
> +    this.disappearingSpeed = FPS / (config.disappearanceTime ?? 2000);
`2000` в константу, можно в этом же файле над классом.

2022-11-14 10:41 UTC, elaineir commented on packages/client/src/pages/Game/core/particle/particles.ts
> +    if (!this.isEndless) {
Конструктор сильно нагружен, нужно вынести условную конструкцию и цикл в методы, например, `initBehavior` для определения поведения и `createParticles` для создания массива частиц

И попробуй сократить количество условий, задав начальное значение для `isDisappearing` прямо в классе, до конструктора.

2022-11-14 10:41 UTC, elaineir commented on packages/client/src/pages/Game/core/particle/particles.ts
> +            (config.particleConfig.maxRadius ?? 20) * random,
`20` тоже стоит вынести в константу

2022-11-14 10:41 UTC, elaineir commented on packages/client/src/pages/Game/core/particle/particles.ts
> +    for (let i = 0; i < this.particleGroup.length; i++) {
Между блоками кода и циклами, а также условными конструкциями лучше добавлять пустую строку для улучшения читаемости

```suggestion
    this.ctx.globalAlpha = this.opacity;
    
    for (let i = 0; i < this.particleGroup.length; i++) {
```

2022-11-14 10:41 UTC, elaineir commented on packages/client/src/pages/Game/core/particle/particles.ts
> +  }
Просто:
```suggestion
  isOutsideCanvas(particle: Particle) {
    return (
      particle.getPosition.x > this.canvas.width + 2 * particle.getRadius ||
      particle.getPosition.x < -2 * particle.getRadius ||
      particle.getPosition.y > this.canvas.height + 2 * particle.getRadius ||
      particle.getPosition.y < -2 * particle.getRadius
    )
  }
```

2022-11-14 10:41 UTC, elaineir commented on packages/client/src/pages/Game/core/particle/particles.ts
> +    }
```suggestion
    if (this.isDisappearing && this.opacity - this.disappearingSpeed > 0) {
      if (this.opacity - this.disappearingSpeed > 0) {
        this.opacity -= this.disappearingSpeed;
      } else {
        this.isDisappeared = true;
      }
    }
```

2022-11-14 10:41 UTC, elaineir commented on packages/client/src/pages/Game/core/particle/stats.ts
> +export const resourceExplode: ParticlesGroupType = {
Вот все эти конфиги лучше разнести по папкам сущностей, чтобы именно они определяли, какие частицы они для себя создают. Файл можно так и назвать `particles`

2022-11-14 10:41 UTC, elaineir commented on packages/client/src/pages/Game/core/particle/stats.ts
> +  const images = [asteroid1, asteroid2, asteroid3, asteroid4];
Этот массив повторяется и в конфиге астероида. Нужно вынести его в константу и использовать в двух методах -- здесь и при конфигурации статов самого астероида.

2022-11-14 10:41 UTC, elaineir commented on packages/client/src/pages/Game/core/particle/stats.ts
> +export function starConfig(): ParticlesGroupType {
Звезды относятся к другой задаче, пока их нужно удалить.

2022-11-14 10:41 UTC, elaineir commented on packages/client/src/pages/Game/core/particle/types.ts
> +  particleNumber: number;
Свойство лучше назвать `quantity`, сейчас, если переводить, получается "номер частицы". Правильнее будет `numberOfParticles`, но `quantity` короче

2022-11-14 10:41 UTC, elaineir commented on packages/client/src/pages/Game/core/entities/sprite/index.ts
>      this.radius = config.radius;
По идее радиус тоже нужно увеличивать, так как этот класс сам по себе независимый. Сейчас если использовать его отдельно вместе со скалированием, то все, что связано с радиусом будет работать неправильно.

То есть отдельно увеличиваем радиус у спрайта, отдельно у его обертки. В сам спрайт передаем изначальный радиус.

2022-11-14 20:42 UTC, Melekh11 commented
спасибо за ревью!

2022-11-15 15:51 UTC, elaineir approved these changes

2022-11-16 11:51 UTC, practicum-maxim-zyryanov approved these changes
Критичных замечаний нет, но пару комментариев оставил.

2022-11-16 11:51 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/Game/core/particles/index.ts
> +          moveAngle: config.moveAngle ?? 2 * Math.PI * random,
Не критично, но выделенный фрагмент кода тяжело читать, здесь рекомендовал бы вынести вычисления redius, position, moveAngle, либо в отдельные функции (если формулы можно использовать повторно), либо поступить как с вычислением random, расположив выше. Код стал бы проще и визуально были бы отделены вычисления от создания объекта.

2022-11-16 11:51 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/Game/core/particles/index.ts
> +    }
Не критично, но здесь небольшое дублирование кода, а при любом копировании есть шансы допустить ошибку. Здесь изменений не ожидаю, но если бы добавлялась новая координата, явно бы фрагмент копировался бы и вот тут и могли что-то упустить и не поправить. Поскольку здесь имеется объект newPos, то рекомендовал бы просто пройти по каждой координате циклом for-in.

2022-11-16 16:59 UTC, Melekh11 commented
спасибо за ревью! :)

2022-11-16 17:01 UTC, merged