feature/AND-35
aranion/game_andromeda pull request #30
Opened 2022-11-16 23:20 UTC by aranion

### Какую задачу решаем
Добавлена возможность изменения данных профиля, пароля и аватарки. Проверки на форму не делал.

2022-11-24 09:14 UTC, HereHaveTheseFlowers approved these changes
Вопросов ничего не вызвало.

2022-11-24 14:42 UTC, practicum-maxim-zyryanov requested changes
Вероятно в код закрался баг - прошу проверить. В остальном к коду вопросов нет, всё хорошо.

2022-11-24 14:42 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/Profile/index.tsx
>    }
В развернутом на vercel.app приложении смотрел. Если сделать Log Out, авторизоваться и сразу перейти на страницу Profile (или любую другую), то получаю ошибку "ID пользователя указан не верно", а в URL содержится **null** в строке https://game-andromeda-client-git-feature-and-35-aranion.vercel.app/profile/null

2022-11-24 14:48 UTC, aranion commented on packages/client/src/pages/Profile/index.tsx
>    }
Да, баг был, я его в каком-то из merge уже поправил, скорее всего когда тестировал SW. Проверю, перенесу изменения.

2022-11-24 18:18 UTC, aranion commented on packages/client/src/pages/Profile/index.tsx
>    }
исправил

2022-11-28 14:28 UTC, aranion commented
исправил

2022-11-28 15:56 UTC, practicum-maxim-zyryanov approved these changes

2022-11-28 16:48 UTC, merged