feature/AND-93
aranion/game_andromeda pull request #31
Opened 2022-11-18 09:51 UTC by Melekh11

### класс для работы с затемнением игрового поля, отображения на нём текста / кнопок

### демо
https://user-images.githubusercontent.com/91600159/202672552-adfcdf30-4224-4aeb-a66d-67dbdf0343fd.mp4

2022-11-18 14:57 UTC, HereHaveTheseFlowers commented
Привет! Как зарезолвишь конфликты пингани меня плиз 🙏

2022-11-20 08:46 UTC, HereHaveTheseFlowers requested changes

2022-11-20 08:46 UTC, HereHaveTheseFlowers commented on packages/client/src/components/Textarea/index.tsx
> +export const Textarea: FC<TextareaProps> = props => {
Немного не понял, при чём тут данный ПР и компонент TextArea. Вроде, он тут нигде не используется. Расскажи, пожалуйста?

2022-11-20 08:46 UTC, HereHaveTheseFlowers commented on packages/client/src/components/Textarea/styles.modules.css
> +.textarea {
Немного не понял, при чём тут данный ПР и компонент TextArea. Вроде, он тут нигде не используется. Расскажи, пожалуйста? [2]

2022-11-20 08:46 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/Game/core/entities/player/index.ts
> +      this.sceneTransition.darkScreen(2000, 5000);
Пока что игра не начинается заного после экрана смерти. Предлагаю поиграть с unmount() и pause(), может даже новый функционал писать не нужно! Если не получится - могу помочь, могу даже ПР сделать отдельный.

2022-11-20 08:46 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/Game/core/map.config.ts
> -      asteroid: 500,
В описании ты нигде не написал, что поменял спавн-рейт астероидов, советую такие штуки отписывать. А изменение поддерживаю, тоже хотел отбалансить это дело. Такие штуки, правда, лучше отдельным ПР-ом про баланс лучше было бы сделать) Ну и пофиг

2022-11-20 08:46 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/Game/core/overworld/scene-transition/index.ts
> +  createButton(buttonConfig: ButtonConfig) {
Реализуй, пожалуйста, этот функционал с помощью реакт-компонента Button. Либо просто создай DOM-елемент button, и накинь на него нужный класс. А то сейчас эта кнопка нарисованная выглядит, мягко говоря, выделяющейся) Да и тут даже никакого эффекта при ховере не сделать.

2022-11-20 08:46 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/Game/core/overworld/scene-transition/stats.ts
> +    console.log('мы кликнули');
Тут стоит вставить функционал начала новый игры. Наверняка просто unmount(), а потом init()

2022-11-20 08:46 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/Game/core/overworld/scene-transition/stats.ts
> +  text: 'Your ship was consumed by cosmic void...',
Знаю, что не ты писал, но 'Your ship was consumed by **_the_** cosmic void...'

2022-11-21 20:26 UTC, Melekh11 commented on packages/client/src/components/Textarea/index.tsx
> +export const Textarea: FC<TextareaProps> = props => {
конфликт мерджа
я взял версии TextArea. Как я понимаю, они бы удалились, я бы я их вырезал при мерджинге, и в develop ушла бы версия без них

2022-11-21 20:29 UTC, Melekh11 commented on packages/client/src/pages/Game/core/map.config.ts
> -      asteroid: 500,
это я менял скорее для быстрой смерти, но согласен, такое нужно писать в начале ПР

2022-11-21 20:36 UTC, Melekh11 commented on packages/client/src/pages/Game/core/entities/player/index.ts
> +      this.sceneTransition.darkScreen(2000, 5000);
pause - это что-то вроде 
```
function pause(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
```
?
или есть что-то встроенное?

2022-11-21 20:55 UTC, Melekh11 commented on packages/client/src/pages/Game/core/overworld/scene-transition/index.ts
> +  createButton(buttonConfig: ButtonConfig) {
думал над этим, но пока не понимаю как его вставлять в canvas

2022-11-21 20:56 UTC, Melekh11 commented on packages/client/src/pages/Game/core/overworld/scene-transition/stats.ts
> +    console.log('мы кликнули');
это будет делать класс GameEvents (отслеживание окончания игры / уровня + вызывать SceneTransition при надобности + в будущем смена карты)
но для демо сделаю!

2022-11-21 20:57 UTC, Melekh11 commented on packages/client/src/pages/Game/core/overworld/scene-transition/stats.ts
> +  text: 'Your ship was consumed by cosmic void...',
ок!

2022-11-21 21:02 UTC, Melekh11 commented on packages/client/src/pages/Game/core/overworld/scene-transition/stats.ts
> +    console.log('мы кликнули');
добавил GameEvents в todo

2022-11-21 21:03 UTC, Melekh11 commented
спасибо за ревью! :))

2022-11-24 09:24 UTC, HereHaveTheseFlowers commented on packages/client/src/components/Textarea/index.tsx
> +export const Textarea: FC<TextareaProps> = props => {
@Melekh11  Немного не понял твой коммент, повтори пожалуйста. Так как мы больше не используем компонент Textarea, тебе нужно удалить его из своей ветки feature/AND-93, и тогда данное ненужное изменение пропадёт : )

2022-11-24 09:29 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/Game/core/entities/player/index.ts
> +      this.sceneTransition.darkScreen(2000, 5000);
Можешь, в принципе, забить. Имплементацию pause() я делал в своем ПР-е, можешь посмотреть [тут](https://github.com/aranion/game_andromeda/pull/34/files#diff-a58a9acdbbbae918d123d8282e2115f07010bbcab8cb3731be80224c8ef92f39). (там всё довольно просто, если есть желание хэтим заниматься может тупо у меня перекопировать).

2022-11-24 09:36 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/Game/core/overworld/scene-transition/index.ts
> +  createButton(buttonConfig: ButtonConfig) {
```JS
// нашли канвас
const currentCanvas = document.querryselector(".canvas");
                 
// создали элемент кнопки
const button = document.createElement('button');

// создаем текст который будет в кнопке
const text = document.createTextNode("New Game");

// вставить текст в кнопку
button.appendChild(text);

// дадим кнопке класс (в нем сделать position: absolute)
button.classList.add("button")
button.classList.add("button__endgame")
                 
// вставим кнопку в канвас
currentCanvas.appendChild(button); ;

```

2022-11-24 09:36 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/Game/core/overworld/scene-transition/index.ts
> +  createButton(buttonConfig: ButtonConfig) {
Если что, обращайся!

2022-11-24 18:28 UTC, aranion commented on packages/client/src/pages/Game/core/overworld/scene-transition/index.ts
> +  createButton(buttonConfig: ButtonConfig) {
В мердже лидерборба в develop при окончании игры срабатывает useEffect на странице, там можно добавить запуск модального окна с кнопками. Надо будет по коду посмотреть можно ли там так сделать.

2022-11-28 21:39 UTC, aranion commented on packages/client/src/pages/Game/core/overworld/scene-transition/index.ts
> +  createButton(buttonConfig: ButtonConfig) {
Думаю можно и такую реализацию оставить. Единственное не происходит сброс игры при проигрыше.

Немного опишу, как можно сделать с redux.
1) Добавить свойство в стейт isgameOver:
![image](https://user-images.githubusercontent.com/71134155/204383232-a78b1286-a353-4eb8-8723-d9850611e90d.png)
2) инициализировать начально значение false и добавить экшен на изменение setIsGameOver:
![image](https://user-images.githubusercontent.com/71134155/204383495-c211242a-5bc5-4164-8ba5-eb612c1b8b24.png)
3) создать компонент `<GameOver />`с получение в пропсах событие которое сработает на кнопку "new game":
![image](https://user-images.githubusercontent.com/71134155/204383754-d787acb0-3c86-4861-9356-646362fe7ad4.png)
![image](https://user-images.githubusercontent.com/71134155/204383957-f152d1fc-f8f1-4fa7-a7c6-e088fb957e07.png)
4) на странице `<Game />` добавить новый компонент `<GameOver />` который будет показан если `isGameOver` в `store` будет `ture`:
![image](https://user-images.githubusercontent.com/71134155/204384512-333847ad-d3db-43af-8bec-d29c87901a92.png)
5) в `handleResetGame` передать экземпляр класса игры который сможет перезапустить игру при нажатии на кнопку `new geme` в компоненте `<GameOver />`
6) в самом классе в месте где нужно вызвать компонент `<GameOver />` нужно заменить значение в `store` 
`store.dispatch(allActions.setIsGameOver(newValue));` где newValue: ture -показать компонент, false - скрыть компонент. Например вот тут:
![image](https://user-images.githubusercontent.com/71134155/204385703-a4528236-15f0-49b2-b033-cfd1bede52bd.png)

Это все про то, как у меня получилось связать класс и компонент. Если не понятно пиши.

2022-11-29 09:00 UTC, HereHaveTheseFlowers commented
Для остальных: Я написал Матвею в ЛС по поводу стайлайзинга кнопки, которое еще нужно поправить, так что подождем чуть-чуть

2022-11-29 09:02 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/Game/core/overworld/scene-transition/index.ts
> +  createButton(buttonConfig: ButtonConfig) {
Плюсую комменту выше, единственное, что - насколько я понимаю, Матвей хочет, чтобы реализовали класс работы с окончанием игры в отдельном ПР-е. Разберемся на этом модуле с этим, думаю. Можно сделать это как задачку на следующем распределении задач

2022-11-29 09:22 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/Game/core/overworld/scene-transition/index.ts
> +  createButton(buttonConfig: ButtonConfig) {
@aranion Я решил в итоге, что реализую этот функционал в своем соседнем ПР-е, причем сразу для gameState, который может быть 'running' (игра идет), 'paused'(игра на паузе) и 'stopped' (игра окончена или еще не началась).

2022-11-29 09:48 UTC, elaineir commented on packages/client/src/pages/Game/core/overworld/scene-transition/index.ts
> +  createButton(buttonConfig: ButtonConfig) {
Нам не нужен редакс, чтобы хранить состояние игры. Модуль игры изначально разрабатывался так, чтобы он не зависел от внешних библиотек.
Но мне уже все равно на самом деле :(

2022-11-29 10:56 UTC, aranion commented on packages/client/src/pages/Game/core/overworld/scene-transition/index.ts
> +  createButton(buttonConfig: ButtonConfig) {
@elaineir Привет! Мы тут учимся, если что-то делаем не так как это принято, пиши, как ты считаешь лучше. В моем случае мне нужен был redux чтобы воспользоваться хуком для отправки данных score на сервер, но можно реализовать отдельный fetch запрос для обновления highScore из класса с игрой, без использования хуков.

2022-11-30 13:32 UTC, HereHaveTheseFlowers approved these changes
Апрув! Пара небольших предложений, что можно изменить:

2022-11-30 13:32 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/Game/game.css
> +  width: 200px;
```suggestion
  width: 250px;
```

Мне кажется, можно чуть изменить тут
![image](https://user-images.githubusercontent.com/106176669/204808395-e42fbd5e-86e3-4580-a4c8-9c62550d957e.png)

2022-11-30 13:32 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/Game/game.css
> +  height: 70px;
```suggestion
  height: 35px;
```

2022-11-30 13:32 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/Game/core/overworld/scene-transition/stats.ts
> +    text: 'new-game',
```suggestion
    text: 'New Game',
```

2022-11-30 13:32 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/Game/core/entities/player/index.ts
>      if (newLives <= 0) {
У меня, когда тесчу, создается сразу несколько инстансов кнопок и лейблов, возможно это происходит здесь. Можем попробовать разобраться, в чем проблема. Пока это транзишн к смерти - всё равно на кол-во создаваемых кнопочек, но если вдруг будет какой то другой функционал - могут возникнуть траблы

![image](https://user-images.githubusercontent.com/106176669/204809158-2d2496a9-72d3-4ef0-95ef-b309d1af4ebc.png)

2022-11-30 14:02 UTC, Melekh11 commented on packages/client/src/pages/Game/core/entities/player/index.ts
>      if (newLives <= 0) {
да, это лучше поправить..
спасибо что нашёл!!

2022-11-30 21:21 UTC, Melekh11 commented on packages/client/src/pages/Game/core/entities/player/index.ts
>      if (newLives <= 0) {
тяк..
я потестил сейчас
проблемы такой не нашёл
она у тебя всё ещё есть?

2022-11-30 21:38 UTC, merged

2022-12-02 11:57 UTC, elaineir commented on packages/client/src/pages/Game/core/overworld/scene-transition/index.ts
> +  createButton(buttonConfig: ButtonConfig) {
@aranion Насколько я помню, мне запретили ревьюить, так что весь код идет мимо меня и вносить предложения зачастую уже поздно.