AND-90 Добавляет меню паузы игры.
aranion/game_andromeda pull request #34
Opened 2022-11-19 20:34 UTC by HereHaveTheseFlowers

### Какую задачу решаем

Добавляет меню паузы, вызываемое по нажатию клавиши 'Esc'. Игра останавливается (добавлен стейт 'paused')

Пока кнопку в игру не добавлял

### Скриншоты/видяшка (если есть)

![image](https://user-images.githubusercontent.com/106176669/202870535-57af0d49-cf0a-4c52-bb3d-a0c25d199b44.png)

2022-11-19 20:36 UTC, HereHaveTheseFlowers commented on packages/client/src/App.test.tsx
> +import { BrowserRouter } from 'react-router-dom';
Два дня пытался найти, почему ругался джест. Оказалось, что вот тут он не мог подтягивать useNavigate, потому что в реальности у нас приложение обернуто в Router, а в тестах - нет. А еще он ругался на абсолютные пути по типу 'src/..'

2022-11-21 09:15 UTC, aranion commented on packages/client/src/pages/Game/index.tsx
> +  const [activePauseMenu, setActivePauseMenu] = useState(false);
Имена для логических выражений обычно пишутся с is или has.
как вариант `[isActivePause, setIsActivePause] = useState(false);`

https://techrocks.ru/2019/05/10/grammar-based-naming-rules/

2022-11-21 09:19 UTC, aranion commented on packages/client/src/pages/Game/index.tsx
> +  });
Думаю компоненту `<Game>` не нужно знать, как и куда перенаправлять пользоталей. Скорее всего лучше все вынести в отдельный компонент, как вариант `<MenuGame>`, который будет отвечать за свою часть.

2022-11-21 09:25 UTC, aranion commented on packages/client/src/pages/Game/index.tsx
> +      <Button></Button>
Не совсем понял зачем `<Button></Button>`

2022-11-21 09:25 UTC, aranion commented on packages/client/src/pages/Game/index.tsx
> +      <Button className='canvas__menu-button' onClick={handleOpenPauseMenu}>
Не нашел на странице кнопку)

2022-11-21 09:30 UTC, aranion commented on packages/client/src/pages/Game/index.tsx
> +    if (newValue) {
как вариант isValue

2022-11-21 09:31 UTC, aranion commented on packages/client/src/pages/Game/index.tsx
> +  document.body.addEventListener('keydown', () => {
срабатыывает на любую кнопку клавиатуры.
Возможно стоит на оброботчике проверять тип нажатой кнопки http://netcode.ru/cpp/?artID=234
Также, было бы неплохо при повторном нажатии вернуться в игру.

2022-11-21 09:32 UTC, aranion commented on packages/client/src/pages/Game/index.tsx
> -        Menu
оооокк :)

2022-11-21 09:34 UTC, aranion commented on packages/client/src/pages/Game/index.tsx
> -        Menu
Ну если задумка была по поводу навесной кнопки в углу для вызова меню, думаю это былобы неплохо.

2022-11-21 10:08 UTC, aranion requested changes
Кнопка работает, все хорошо, но думаю стоит внести изменения в "архитектуру".
1)	Отдельный компонент `<GameMenu/>`. 
2)	У нас нет навигации в проекте, если рассматривать другие игры с управление мышкой, стоит поместить кнопку (по аналогии `<ButtonBack>`) вызова меню на все экраны в приложении. То есть вынести на самый верхний уровень `<App>`
3)	В зависимости от «path» из роутера показывать необходимый набор кнопок. ( для `<Game>`(play, resume), для остальных страниц (game, Profile, leader ..), убрать кнопку меню на` <SignIn> и <SignUp>`). 
4)	По нажатию «Esc» показывать меню, и скрывать, если оно открыто. 
5)	Нет смысла создавать отдельную страницу, для меню приложения, при авторизации нас должно перенаправлять на страницу «/game» с уже открытым меню и кнопкой «Play» / «Start Game» и остановленной игрой. Дальше пользователь сам выбирает запустить ему игру или перейти в другой раздел. Т.е. `<GameMenu/>` не отдельная струнца, а модальное окно.
6)	имхо. Одинаковая ширина кнопок в меню смотрится как-то приятнее. Logout поместить к остальным кнопкам.

2022-11-24 19:44 UTC, aranion commented
после мерджа пофиксил возникшие конфликты, добавил mock пакет для тестов, сделай yarn install чтобы установить

2022-11-29 11:54 UTC, HereHaveTheseFlowers commented
@aranion 
Сделал практически всё, о чем ты говорил в ревью:

_1. Отдельный компонент <GameMenu/>._ **- Сделано. Называется PauseMenu, потому что главное меню уже есть. В будущем, можно будет упразднить одно из них в пользу другого, но это когда разберемся до конца с началом и окончанием игры.**

_2. У нас нет навигации в проекте, если рассматривать другие игры с управление мышкой, стоит поместить кнопку (по аналогии <ButtonBack>) вызова меню на все экраны в приложении. То есть вынести на самый верхний уровень <App>_ - **Сделано, PauseMenu находится в App**


_3. В зависимости от «path» из роутера показывать необходимый набор кнопок. ( для <Game>(play, resume), для остальных страниц (game, Profile, leader ..), убрать кнопку меню на <SignIn> и <SignUp>)._ - **Сделано**


_4. По нажатию «Esc» показывать меню, и скрывать, если оно открыто._ - **Сделано, КРОМЕ скрывания при повторном нажатии. Долго игрался с Callback и AddEventListener, но так ничего и не придумал. Проблема в том, что навешивается сразу несколько Event Listener'ов**


_5. Нет смысла создавать отдельную страницу, для меню приложения, при авторизации нас должно перенаправлять на страницу «/game» с уже открытым меню и кнопкой «Play» / «Start Game» и остановленной игрой. Дальше пользователь сам выбирает запустить ему игру или перейти в другой раздел. Т.е. <GameMenu/> не отдельная струнца, а модальное окно._ - Не сделано, пока что у нас кроме паузы есть и GameMenu. Упраздним последнее, когда разберемся со сценой в начале игры и окончанием.


_6. имхо. Одинаковая ширина кнопок в меню смотрится как-то приятнее. Logout поместить к остальным кнопкам._ - **Готово!**

2022-11-29 11:54 UTC, HereHaveTheseFlowers commented
Только чтото Vercel отказался взаимодействовать со мной)

2022-11-29 22:42 UTC, aranion reviewed
Все работает! Молодец! Хорошо получилось
Кое что можно подправить.

2022-11-29 22:42 UTC, aranion commented on packages/client/src/pages/Game/index.tsx
>      <>
в таком случае `<></>` лишнее тут

2022-11-29 22:42 UTC, aranion commented on packages/client/src/pages/Game/index.tsx
> +  const gameStatus = useTypeSelector(gameSelectors.gameStatus);
В целом одно и тоже, но если нужно достать несколько элементов из `store`, а не один вот такая запись выглядит чище: `const { hightScore, gameStatus } = useTypeSelector(gameSelectors.all);`

2022-11-29 22:42 UTC, aranion commented on packages/client/src/pages/Game/index.tsx
> +    if (gameStatus && game && game.current) {
`(gameStatus && game && game.current)` возможно можно упростить? `(gameStatus && game?.current)`

2022-11-29 22:42 UTC, aranion commented on packages/client/src/components/PauseMenu/index.tsx
> +      <>
Родительская обертка уже есть, можно не добавлять `<></>`

2022-11-29 22:42 UTC, aranion commented on packages/client/src/components/PauseMenu/index.tsx
> +      store.dispatch(gameActions.setGameStatus('paused'));
Для типизации `store` и упрощение кода был добавлен хук `useActions`.
Он довольно простой, но очень помогает)
он сразу вызывает `dispatch` для экшенов и типизирует все экшены из store.
Использовать можно как и `useTypeSelector` вот так: `const { setGameStatus } = useActions();` и с ним работать как с методом `setGameStatus('paused');`
То есть вместо `store.dispatch(gameActions.setGameStatus('paused'));` будет `setGameStatus('paused');`

2022-11-29 22:42 UTC, aranion commented on packages/client/src/components/PauseMenu/index.tsx
> +  const pathname = document.location.pathname;
В реакте есть `useLoacation` для получения данных из URl строки браузера, лучше его использовать.
`const { pathname } = useLocation();` там есть полезные свойства 
![image](https://user-images.githubusercontent.com/71134155/204655108-9bbdabd9-4e57-4f7a-8ad0-e3ad7554d94b.png)

2022-11-29 22:42 UTC, aranion commented on packages/client/src/App.tsx
>        </main>
лучше наверное все поднять в main:
`<main className={cls.app__content}>
        <Router />
        <ButtonFullscreen elemRef={fullscrinableElem} />
        <PauseMenu />
      </main>`

2022-11-29 22:42 UTC, aranion commented on packages/client/src/components/Modal/styles.modules.css
> +  z-index: 9999;
Лучше не присваивать максимальное значение 9999, если потребуется вывести элемент выше, придётся понижать этот.

2022-11-29 22:42 UTC, aranion commented on packages/client/src/components/PauseMenu/index.tsx
> -import { useState, useCallback } from 'react';
Набросал кое какие изменения в этом файле:

```
import { useEffect, useState } from 'react';
import { Button, Modal } from 'src/components';
import { useLocation, useNavigate } from 'react-router-dom';
import { RouterList } from 'src/router/routerList';
import { gameSelectors } from 'src/store/game';
import { useTypeSelector } from 'src/hooks/useTypeSelector';
import { userSelectors } from 'src/store/user';
import { useActions } from 'src/hooks/useActions';

export function PauseMenu() {
  const [isActivePause, setIsActivePause] = useState(false);

  const navigate = useNavigate();
  const { pathname } = useLocation();

  const gameStatus = useTypeSelector(gameSelectors.gameStatus);
  const { userData } = useTypeSelector(userSelectors.all);

  const { setGameStatus } = useActions();

  const { id } = userData;
  const isGamePage = pathname === '/game';
  const isNotHomePage = pathname !== '/';
  const isNotLeaderBoardPage = pathname !== '/leader-board';
  const isNotProfile = !pathname.includes('/profile');
  const isNotForum = !pathname.includes('/forum');
  const isSignUpOrInPage = pathname.includes('/sign');

  useEffect(() => {
    document.body.addEventListener('keydown', handlePause);

    return () => {
      document.body.removeEventListener('keydown', handlePause);
    };
  }, []);

  const setIsActivePauseMutated = (isValue: boolean) => {
    if (gameStatus === 'stopped') return;
    if (isValue) {
      setGameStatus('paused');
    } else {
      setGameStatus('running');
    }
    setIsActivePause(isValue);
  };

  const handleTogglePauseMenu = () => {
    setIsActivePauseMutated(!isActivePause);
  };

  const navigateHome = () => {
    navigate(RouterList.HOME);
    handleTogglePauseMenu();
  };

  const navigateGame = () => {
    navigate(RouterList.GAME);
    handleTogglePauseMenu();
  };

  const navigateForums = () => {
    navigate(RouterList.FORUM);
    handleTogglePauseMenu();
  };

  const navigateProfile = () => {
    navigate(`${RouterList.PROFILE}/${id}`);
    handleTogglePauseMenu();
  };

  const navigateLeaderboard = () => {
    navigate(RouterList.LEADER_BOARD);
    handleTogglePauseMenu();
  };

  const navigateBack = () => {
    navigate(-1);
    handleTogglePauseMenu();
  };

  const handlePause = (event: KeyboardEvent) => {
    const { repeat, key } = event;

    if (!repeat && key === 'Escape') {
      handleTogglePauseMenu();
    }
  };

  if (isSignUpOrInPage || !isNotHomePage) {
    return null;
  }

  return (
    <Modal active={isActivePause} setActive={setIsActivePauseMutated}>
      {!isGamePage && <Button onClick={navigateGame}>Play</Button>}
      {isGamePage && <Button onClick={handleTogglePauseMenu}>Resume</Button>}
      {isNotProfile && <Button onClick={navigateProfile}>Profile</Button>}
      {isNotForum && <Button onClick={navigateForums}>Forums</Button>}
      {isNotLeaderBoardPage && (
        <Button onClick={navigateLeaderboard}>Leaderboard</Button>
      )}
      {isSignUpOrInPage && <Button onClick={navigateBack}>Back</Button>}
      {isNotHomePage && <Button onClick={navigateHome}>Back to Menu</Button>}
    </Modal>
  );
}

```

2022-11-29 22:42 UTC, aranion commented on packages/client/src/pages/Game/core/index.ts
> +type GameStatus = 'stopped' | 'paused' | 'running';
Возможно стоит вынести в enum и использовать его везде где нужен статус.  уже заметил в двух местах (PAuseMenu) использование строк для сравнения. 
`export enum GameStatusList {
 stopped = 'stopped' , paused = 'paused' , running =  'running'}`

2022-11-29 22:42 UTC, aranion commented on packages/client/src/pages/Game/core/index.ts
> +  private status: GameStatus = 'stopped';
вот тут тоже строка, лучше через enum

2022-11-29 22:42 UTC, aranion commented on packages/client/src/pages/Game/core/index.ts
> +      if (this.status === 'stopped') {
опять строка

2022-11-29 22:42 UTC, aranion commented on packages/client/src/store/game/slice.ts
> +  gameStatus: 'running',
ну ты понял, опять строка)

2022-11-29 22:42 UTC, aranion commented on packages/client/src/store/game/type.ts
> +  gameStatus: 'running' | 'paused' | 'stopped';
enum
`typeof keyof GameStatusList` вернет из enum ключи как строки

2022-12-11 14:08 UTC, HereHaveTheseFlowers commented on packages/client/src/store/game/type.ts
> +  gameStatus: 'running' | 'paused' | 'stopped';
По какой-то причине не могу заставить это работать, хмм

![image](https://user-images.githubusercontent.com/106176669/206908479-ffc4057b-230d-481f-a052-66c37e8340bb.png)

2022-12-11 14:24 UTC, HereHaveTheseFlowers commented
@aranion Спасибо тебе большое за подробное ревью💯, я всё учёл и исправил.

2022-12-11 17:39 UTC, aranion commented on packages/client/src/store/game/type.ts
> +  gameStatus: 'running' | 'paused' | 'stopped';
хм, я перепутал порядок, `keyof typeof GameStatusList`

2022-12-11 17:50 UTC, aranion approved these changes

2022-12-11 17:51 UTC, aranion commented
Все отлично! Vercel поправил, игра доступна https://game-andromeda-client-8v273uamq-aranion.vercel.app/

2022-12-13 14:32 UTC, practicum-maxim-zyryanov approved these changes

2022-12-15 10:37 UTC, merged