AND-96 Добавляет MediaAPI
aranion/game_andromeda pull request #45
Opened 2022-12-17 08:45 UTC by HereHaveTheseFlowers

### Какую задачу решаем

Добавляет Media API, сделал его через редюсеры Redux Store. Подскажите плиз, если вдруг такие вещи, как playSound() нужно было не через редюсеры а что-то другое.

Функционал  такой:
При создании приложения в useEffect() подгружаем все звуки через "addSound", причем главную тему игры с включенной опцией "playWhenLoaded", чтобы заиграло сразу, как скачалось.
Далее в совершенно любом месте можно обратиться к Redux Store с помощью ```store.dispatch(soundActions.playSound({ soundURL: 'spark.mp3', volume: 0.3 }));```, чтобы сыграть звук, остановить звук, тд. Опции: громкость, зацикленное воспроизведение.

Также добавлена кнопка чтобы заглушить звук игры. Она ставит глобальную громкость всем звукам на 0. 

Нафигачил в Аблетоне главную темку для игры, пару звуков и темку для босса, чтобы не долбиться с копирайтом)
Послушать можно [тут](https://drive.google.com/drive/folders/16mgEHErqbUu45k_bpULN52_nFYm_dGio?usp=sharing)

### Скриншоты/видяшка (если есть)

Качество не очень, лучше сами попробуйте.

https://user-images.githubusercontent.com/106176669/208232733-90486814-9e53-4146-a5e8-6939d0ec6352.mp4

2022-12-20 20:16 UTC, aranion requested changes

2022-12-20 20:16 UTC, aranion commented on packages/client/src/App.tsx
> +import { store } from './store';
Работа со store в компонента происходит через hook или HOK(Higher-Order Components). В функциональных компонентах можно вызвать хук useTypeSelector(state => state) - (это просто типизированный useSelector(state => state)) и получить доступ к данным в Store. При взаимодействие со Store используется хук useActions() - (это просто обернутый в типизацию и автоматическое добавление dispatch(action) к экшенам).
То есть, внутри компонента нужно вызвать:
` const { addSound, } = useActions();` использовать `addSound({ soundURL: 'bosstheme.mp3' })`
для получения данных из стора:
`const { soundURLs, soundSources, globalVolume} = useTypeSelector(state => state. sound)` причем тут вот эту часть лучше вынести в отдельный `selectors.ts` в store, так уменьшается количество рендеринга(https://habr.com/ru/post/564004/), получается: 
`import type { RootState } from '../getInitialState';
export const all = (state: RootState) => state.sound;`
в index.ts где sound `export * as soundSelectors from './selectors';`
используем вместо `useTypeSelector(state => state. sound)` на `useTypeSelector(soundSelectors.all)`

2022-12-20 20:16 UTC, aranion commented on packages/client/src/App.tsx
> +    store.dispatch(soundActions.addSound({ soundURL: 'bosstheme.mp3' }));
`const { addSound } = useActions()` 
и
`addSound({ soundURL: 'bosstheme.mp3' })` вместо `store.dispatch(soundActions.addSound({ soundURL: 'bosstheme.mp3' }));`

2022-12-20 20:16 UTC, aranion commented on packages/client/src/App.tsx
> +    store.dispatch(soundActions.addSound({ soundURL: 'spark.mp3' }));
Возможно стоит сразу разместить дынные soundURL в initialState?

2022-12-20 20:16 UTC, aranion commented on packages/client/src/components/ButtonSoundOption/index.tsx
> +import { store } from 'src/store';
убарть

2022-12-20 20:16 UTC, aranion commented on packages/client/src/components/ButtonSoundOption/index.tsx
> +import { soundActions } from 'src/store/sound';
тоже, выше описал

2022-12-20 20:16 UTC, aranion commented on packages/client/src/components/ButtonSoundOption/index.tsx
> +
`const { setGlobalVolume } = useActions()`
и
`setGlobalVolume({ volume: 0 })` вместо ` store.dispatch(soundActions.setGlobalVolume({ volume: 0 }))`

2022-12-20 20:16 UTC, aranion commented on packages/client/src/pages/Game/core/entities/resource/index.ts
> +    store.dispatch(
тут я другого способа не знаю, как  обратиться к store вне компонента, можно оставить так

2022-12-20 20:16 UTC, aranion commented on packages/client/src/store/sound/selectors.ts
> +export const all = (state: RootState) => state.sound;
selectors.ts уже оказывается есть

2022-12-20 20:16 UTC, aranion commented on packages/client/src/store/sound/slice.ts
> +      }>
`PayloadAction<{
        soundURL: string;
        playWhenLoaded?: 'continuous' | 'once';
      }` 
вынос в отдельный тип возможно будет лучше 
`
type AddSound = {
        soundURL: string;
        playWhenLoaded?: PlayWhenLoaded
      };
type PlayWhenLoaded = 'continuous' | 'once';`

`...PayloadAction<AddSound>...`

2022-12-20 20:16 UTC, aranion commented on packages/client/src/store/sound/slice.ts
> +      state.soundSources.push(audio);
Изменение state напрямую, не через action недопустимы же? 
Думаю стоит использовать actions на изменения через dispatch.
Если я правильно понимаю тут нужно вводить thunk или saga.

Возможно стоит рассмотреть вынос логики в хук, по аналогии с useAuth, там можно обратиться к store через dispatch

2022-12-20 20:16 UTC, aranion commented on packages/client/src/store/sound/slice.ts
> +function checkMediaSourceSupport(mime: string) {
Вспомогательные функции лучше вынести отдельно в utils.ts

2022-12-20 20:16 UTC, aranion commented on packages/client/src/store/sound/type.ts
> +  soundSources: any;
`soundSources: SoundSource[];`
`
type SoundSource = {
volume: number | boolean;
src: string;
textContent: string;
pause: () => Promise<any>;
currentTime: number;
duration: string;
ontimeupdate?: () => {} 
}`
примерно..., возможно есть уже реализованный тип для audio файлов

2022-12-24 11:51 UTC, HereHaveTheseFlowers commented on packages/client/src/store/sound/type.ts
> +  soundSources: any;
Тут HTMLAudioElement[] просто, насколько я понимаю. Спасибо, что заметил, я тут забыл что-то any поменять

2022-12-24 12:00 UTC, HereHaveTheseFlowers commented on packages/client/src/App.tsx
> +    store.dispatch(soundActions.addSound({ soundURL: 'spark.mp3' }));
Если честно, немного не понял, что ты имел под этим в виду? Каким то другим образом добавлять звуки в игру? или в другом месте

2022-12-24 12:08 UTC, HereHaveTheseFlowers commented on packages/client/src/store/sound/slice.ts
> +      state.soundSources.push(audio);
Хмм, а почему тогда к примеру в других слайсах меняем напрямую?? К примеру в игровом slice.ts есть ```state.gameStatus = payload;```

2022-12-26 15:44 UTC, HereHaveTheseFlowers commented
@aranion  Спасибо тебе огромное за ревью. Поправки заняли много времени, потому что пришлось полностью всё переписывать (подробнее расскажу на синке), но вкратце:

- Аудио формата mp3 не зациклить идеально, всегда будет небольшая пауза, поэтому для таких звуков используем .wav, у него такой фигни нет.
- Вместо MediaSource API теперь Audio Web API, которое НАМНОГО лучше, и поддерживает .wav. Также поддерживает seamless audio looping с помощью loop = true.
- Т.к. теперь используем Audio Web API, логика полностью переписана под него.
- Намного укоротил длинные аудио файлы
- Перенёс часть логики в HOC, как ты предложил. Но включать звуки всё еще можно из любой части кода через редюсер.
- Jest при тестировании ругается на AudioContext(), поэтому используем мок для него (как обычно ошибки с джестом занимают у меня по пол дня ахахахах)

2022-12-26 20:15 UTC, aranion approved these changes
Все хорошо, работает, молодец!
На развитее можно добавить звуки для взаимодействия с астероидами, стрельбы, при подборе улучшений.

2022-12-26 20:15 UTC, aranion commented on packages/client/src/store/sound/slice.ts
> +      state.soundSources.push(audio);
Да, ты все верно сделал, я что-то забыл что тут Redux Toolkit, тут можно)

2022-12-26 20:15 UTC, aranion commented on packages/client/src/App.tsx
> +    store.dispatch(soundActions.addSound({ soundURL: 'spark.mp3' }));
Оставляй так, я сначала думал что тут идет просто запись имени файлов в стор, а тут происходит подготовка аудио "обектов".  

Возможно можно переписать чтобы addSound принимал не по штучно, а массив?
`addSound([
{ soundURL: 'bosstheme.mp3' },
{ soundURL: 'shoot1.mp3' },
{ soundURL: 'shoot2.mp3' },
{ soundURL: 'spark.mp3' },
{
        soundURL: 'maintheme.mp3',
        playWhenLoaded: 'continuous',
},
{ soundURL: 'shoot.mp3' }
]);`

и уже в store addSound пробежаться по массиву и вызвать для каждого элемента создание аудио?

2022-12-26 20:15 UTC, aranion commented on packages/client/src/store/sound/type.ts
> +  audioBuffer: AudioBuffer | 'loading';
'loading' довольно часто встречается по коду, возможно стоит вынести в енум или константу.

2022-12-26 20:15 UTC, aranion commented on packages/client/src/store/sound/slice.ts
> +          document.createElement('audio');
Могу ошибаться, но тут на каждый playAudio создается новый элемент?
Возможно стоит при очистке интервала чистить за собой элементы?:
```
.then(() => {
              bufferSource.start(0);
              clearInterval(tryToPlay);
             testAudio = null;
            })
            .catch(() => {
              console.info('User has not interacted with document yet.');
            }).finaly(() => {testAudio .remove()});
```

2022-12-26 20:15 UTC, aranion commented on packages/client/src/store/sound/slice.ts
> +          audioBuffer: audioBuffer,
аналогично записи
```
state.loadedSounds.push({
          soundURL,
          audioBuffer,
  audioSource,
})
```

2022-12-26 20:15 UTC, aranion commented on packages/client/src/hooks/useAudio.ts
> +    playAudio({ soundURL: soundURL, continuous: continuous });
аналогично записи:
`playAudio({ soundURL, continuous});`

2022-12-26 20:15 UTC, aranion commented on packages/client/src/hooks/useAudio.ts
> +  const { store } = useContext(ReactReduxContext);
`const { store } = useContext(ReactReduxContext);`
так, что-то тут не то)
не ну вроде проблем нет, но возможно можно просто использовать useSelector() для доступа к строе? :)

2022-12-26 20:15 UTC, aranion commented on packages/client/src/hooks/useAudio.ts
> +  const { store } = useContext(ReactReduxContext);
`const loadedSounds = useTypeSelector(soundSelectors.loadedSounds)`
или 
`const {loadedSounds } = useTypeSelector(soundSelectors.all)`
или 
`const {loadedSounds } = useTypeSelector(state => state.sound)`
 useTypeSelector тоже что и  useSelector но с типизацией нашего сторе.

2022-12-26 20:15 UTC, aranion commented on packages/client/src/hooks/useAudio.ts
> +    for (const loadedSound of store.getState().sound.loadedSounds) {
`const loadedSounds = useTypeSelector(soundSelectors.loadedSounds)`
и
`for (const loadedSound of loadedSounds) `

2022-12-27 08:48 UTC, HereHaveTheseFlowers commented on packages/client/src/store/sound/slice.ts
> +          document.createElement('audio');
@aranion Блин, что-то я не доглядел, думал сборщик мусора удаляет и элемент когда я делаю testAudio = null. Спасибо, что заметил! Я  просто перед добавлю ```testAudio.remove()``` перед ```testAudio = null```

2022-12-27 08:55 UTC, HereHaveTheseFlowers commented on packages/client/src/hooks/useAudio.ts
> +  const { store } = useContext(ReactReduxContext);
@aranion Да, я изначально так и сделал (выше на строчку можешь заметить), но по какой-то неизвестной мне причине loadedSounds не обновляется и просто  остается пустым массивом, если использую useTypeSelector. А вот если подтягиваю напрямую из store, то всё ок. Много чего перепробовал, в итоге пришлось использовать такой костыль. Есть идеи, с чем это может быть связано?

2022-12-27 12:15 UTC, aranion commented on packages/client/src/hooks/useAudio.ts
> +  const { store } = useContext(ReactReduxContext);
Нужно будет код потыкать, вечером, думаю не критично, можно и так оставить

2022-12-27 19:21 UTC, HereHaveTheseFlowers commented on package.json
> +}
```suggestion
}

```

2022-12-27 19:33 UTC, HereHaveTheseFlowers commented
@practicum-maxim-zyryanov и этот пр тоже заапрувь если не трудно!

2022-12-28 07:12 UTC, aranion commented
Подправил useAudio, данные получает из useSelector. Типизацию тоже немного поправил.
Браузеры по умолчанию отключают автовоспроизведение звука на сайте, пользователю необходимо произвести клик по любой области, чтобы началось воспроизведение https://habr.com/ru/company/globalsign/blog/439118/

2022-12-28 07:14 UTC, HereHaveTheseFlowers commented
Спасибо большое. Угу, я для этого создал tryToPlay которое каждые две секунды проверяет, можем ли включать аудио, с помощью testSound.

2022-12-28 10:34 UTC, HereHaveTheseFlowers commented on packages/client/src/components/ButtonSoundOption/styles.module.css
> +  right: 95px;
```suggestion
  right: 20px;
```

2022-12-28 10:34 UTC, HereHaveTheseFlowers commented on packages/client/src/components/ButtonSoundOption/styles.module.css
> +  top: 20px;
```suggestion
  top: 90px;
```

2022-12-28 15:54 UTC, practicum-maxim-zyryanov approved these changes
Ничего критичного... Approve

2022-12-28 15:54 UTC, practicum-maxim-zyryanov commented on packages/client/src/hooks/useAudio.ts
> +  };
Хотя код и разбит на блоки, код всё равно сложно читать: очень большая функция, смешение различных уровней абстракции, здесь же обработка ошибок - посоветовал бы вынести отдельные по смыслу блоки в отдельные функции.

2022-12-29 08:22 UTC, HereHaveTheseFlowers commented
@practicum-maxim-zyryanov Спасибо за подсказку, я перенёс логику "проверки когда можем включать звук" tryToPlay в отдельную функцию whenAudioCanPlay, а еще почистил addSound, на который ты указал, просто заменив кучу кода на playAudio (не знаю, почему не сделал это раньше)

@aranion Я, кстати, проверил - после того, как ты подправил useAudio, вернув loadedSounds в useSelector, главная темка снова включается дважды, потому что loadedSounds снова не обновляется и является пустым массивом. :-(((
Пока что вернул его проверку через store. Как думаешь, оставить так, или поищем еще какие то фиксы проблемы?

2023-01-11 08:09 UTC, HereHaveTheseFlowers commented
В итоге, я так и не нашел фикса проблемы, предлагаю просто замержить, и если кто-то в будущем сможет сделать без использования прямого вызова store, то будет круто.

2023-01-11 08:12 UTC, aranion commented
Оставляй. Думаю у нас есть чем еще заняться)

2023-01-12 16:08 UTC, merged