feature/AND-72 Создание базового движка игры с игровым циклом
aranion/game_andromeda pull request #6
Opened 2022-10-28 12:24 UTC by elaineir

### Какую задачу решаем
Реализация базового движка игры с игровым циклом и базовое управление моделью игрока на нем (следует за курсором мышки). Визуальное представление игрока на данном этапе -- красный круг.

### Скриншоты/видяшка
![preview](https://user-images.githubusercontent.com/75016726/198586074-ed46a404-257e-4df5-b659-48573f99078c.gif)

2022-10-29 15:42 UTC, HereHaveTheseFlowers approved these changes
Всё отлично, не нашел ничего, что я бы сейчас изменил.

2022-10-30 10:29 UTC, practicum-maxim-zyryanov requested changes
Ничего критичного, но есть смешение уровней абстракций, избыточные комментарии и тест, название которого вводит в заблуждение.

2022-10-30 10:29 UTC, practicum-maxim-zyryanov commented on packages/client/src/App.test.tsx
>  test('Example test', async () => {
**Не критично, но лучше сразу поправить**
Изменен тест, но не изменено название. Если тест начнёт падать, то легко не придать значение падению "Example test", поэтому стоит сразу прояснить назначение теста и описать, что это, к примеру, тест инициализации канваса.

2022-10-30 10:29 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/Game/core/entities/game-object/index.ts
> +    this.radius = config.radius ?? 15;
**Можно лучше**
Магические числа 15 и 100 рекомендую вынести в константы, в конфиг, т.к. есть большая вероятность, что дефолтные значения начнут всплывать и в других частях логики позже. Также не ясно почему выбраны такие значения, а имя констант могло бы это прояснить. К примеру, у констант MIN_SPEED, MAX_SPEED, INITIAL_SPEED может быть значение 100, но встретив имя, становится понятнее, как с ними работать и что от них ждать.

2022-10-30 10:29 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/Game/core/entities/player/stats.ts
> +  speed: 100,
Вот кстати и второй раз всплыло значение 100, и здесь расскажу ещё об одной пользе констант. Вот здесь, например, не знаю эти 100 это тоже самое по смыслу значение, что и 100 ранее? Вполне обычная ситуация, когда 100 встречается как значение в разных константах и если возникнет необходимость поправить одно из них, сделав равным 75, то потребуется очень много времени, чтобы определить какое 100 можно трогать, а какое нет.

2022-10-30 10:29 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/Game/core/index.ts
> +  /** Синглтон, чтобы не создавалось несколько копий из-за реакта */
**Можно лучше**
В коде много избыточных комментариев, но комментарии обычно не поддерживаются разработчиками с той же ответственностью, как и код. Причина проста: ошибка в коде - код не работает, ошибка в комменте - всё норм. В итоге, комментарии быстро устаревают, могут быть ошибочными и вообще начать вводить в заблуждение. Например, здесь могло быть принято решение, больше не делать объект синглтоном, например для упрощения тестирования, и тогда комментарий начал бы вводить разработчиков в заблуждение.

Тем не менее, то, что здесь вообще упоминается паттерн - очень хорошо. Но стоит это делать не в комментарии, а прямо в имени сущности, например договориться, что Instance = Singleton.

Вывод: чем меньше комментариев - тем лучше, всю полезную информацию следует сообщать в коде

2022-10-30 10:29 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/Game/core/index.ts
> +    }
**Можно лучше**

Мне нравится, что в коде проверяются предварительные условия, например, что контекст инициализирован. Но весь этот кусок из инициализаций и проверок находится на уровне более низких абстракций, поэтому стоит вынести его в обособленный метод, например initCanvas(config: GameConfig): Canvas

Тогда в конструкторе останется только работа с абстракциями уровня игры: канвасом, направлениями, игроком и т.д.

2022-10-30 10:29 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/Game/core/index.ts
> +        this.frame++;
Есть лёгкое ощущение, что и здесь мешаются абстракции разных уровней, т.к. используется this.canvas.width, this.canvas.height, а для игрока не используется понятие размеров, т.е. он инкапсулирует это знание в себе. Возможно стоит и поле игры представить как игровой объект, которому можно дать команду себя отрисовать, например выделить объект Map.

Ещё рекомендую вынести всё отрисовку в отдельный метод, т.к. этот метод делает много работы на разных уровнях абстракций, и фреймрейт считает, и задержки, и здесь же рисует. Т.е. весь кусок от last = now и до this.frame++ так и просится в отдельный метод.

2022-10-30 11:20 UTC, elaineir commented on packages/client/src/pages/Game/core/index.ts
> +  /** Синглтон, чтобы не создавалось несколько копий из-за реакта */
Эти комментарии в основном для большей поддержки подсказок IDE, чтобы при наведении на поле где-то в коде понять, что это и для чего, не проваливаясь в код класса и не скроллить туда-сюда лишний раз. Для автогенерации документации тоже вроде как используются, например, в TSDoc и для сторибука (описание компонентов и типов).
Если сильно мешают, то удалю.

2022-10-30 11:28 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/Game/core/index.ts
> +  /** Синглтон, чтобы не создавалось несколько копий из-за реакта */
Если для документации, тогда вопросов нет. Отлично, что учтено. Но всегда стоит помнить про то, что в какой-то момент эти записи могут разойтись с логикой. Мне доводилось встречать документацию на реальных проектах, которая не имела ничего общего с реально описанной логикой метода. Поэтому предпочитаю, когда само определение несёт необходимую информацию.

2022-10-30 11:39 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/Game/core/index.ts
> +  /** Синглтон, чтобы не создавалось несколько копий из-за реакта */
Во фрагменте ниже комментарий очень уместный, он дополнительно поясняет логику.

```
/** Скорость перемещения объекта. Чем выше значение, тем медленнее. */
protected speed: number;
```

Вспомнил ещё важный момент про комментарии для документации. Обычно их стоит применять, если у разработчика нет доступа к коду метода. Например, делается публичный API, и у пользователя API нет возможности заглянуть внутрь. Если же это внутренний код команды, где каждый может провалиться к определению метода и посмотреть, необходимость комментария вызывает вопросы.

2022-10-31 10:58 UTC, elaineir commented
- Исправлено название теста
- Добавлены константы INITIAL_SPEED и INITIAL_RADIUS
- Канвас и контекст оставлен только в Game
- Удалены комментарии к свойствам и методам
- gameInstance -> singleton
- в game добавлены методы initCanvas и render
- GameMap рисует фон канваса и дает инструкции игроку

2022-10-31 11:52 UTC, practicum-maxim-zyryanov requested changes

2022-10-31 11:52 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/Game/core/entities/player/index.ts
> +}
**Можно лучше**
Обратил внимание на переменную ctx, она напомнила мне про запах кода "G14: Функциональная зависть", т.е. класс настолько часто работает с переменной ctx и заставляет передавать её почти каждому методу, что создается ощущение, что в классе ctx и не хватает. Можно передавать переменную прямо в конструктор при создании объекта, это сделает код чище, т.к. параметров методов станет заметно меньше, в том числе уйдёт параметры canvasWidth и canvasHeight в keepInsideCanvas, а также width и height в методе update. 

Скорее всего это общая логика для всех подклассов GameObject, поэтому рекомендую рассмотреть вопрос установки свойства контекста в родительском классе.

2022-10-31 12:49 UTC, practicum-maxim-zyryanov approved these changes

2022-10-31 12:57 UTC, merged