feature/AND-18 Добавляет страницы Входа и Регистрации
aranion/game_andromeda pull request #7
Opened 2022-10-30 10:29 UTC by HereHaveTheseFlowers

### Какую задачу решаем
- Добавляет страницы Входа и Регистрации. Дизайн идентичен [макету на фигме](https://www.figma.com/file/httxU5fgDr1IYMHcfN2Jvu/Andromeda-game?node-id=0%3A1).
- Добавляет normalize.css в папку vendor.
- Добавляет в index.css переменные, отвечающие за цвет:  `color-bg, color-normal, color-light, color-highlight`
- Добавляет библиотеку `classnames` по предложению @elaineir 
- Подключает шрифт `Audiowave` в link index.html.
- **Добавляет компоненты: Button, Input, Star** (для декорации фона).
- Добавил стилей компоненту Loader.

### Скриншоты/видяшка
<details>
  <summary>Кликни на меня 👾 </summary>
  
![127 0 0 1_3000_sign-in](https://user-images.githubusercontent.com/106176669/198873599-8cc7035f-9972-4396-a153-b115a00d88ed.png)
![127 0 0 1_3000_sign-in (1)](https://user-images.githubusercontent.com/106176669/198873600-a7c5b938-7ee2-4510-8ec2-f1163f486a14.png)
<img src="https://user-images.githubusercontent.com/106176669/198873598-6d7331b9-2284-41d8-95e5-26ade847b410.png" alt="127 0 0 1_3000_sign-in(iPhone 12 Pro)" width=30%>

</details>

2022-10-30 10:34 UTC, HereHaveTheseFlowers commented
Review-ready 😵‍💫

2022-10-30 16:32 UTC, aranion commented on packages/client/src/components/Button/Button.tsx
> +export default Button;
Двойной экспорт: defaultм и именованный компонента Button, тут не опечатка? Наверное предпочтительней оставить только именованный?

2022-10-30 16:38 UTC, aranion commented on packages/client/src/components/Input/Input.tsx
> +            <input placeholder={this.props.placeholder} onChange={this.props.onChange} className={classNames}/>
Чтобы не писать длинные цепочки this.props.placeholder, возможно стоит сделать деструктуризацию? 
`const {placeholder, onChange} = this.props; `
и потом использовать, как переменные:  
`<input placeholder={placeholder} onChange={onChange} className={classNames}/>`

2022-10-30 16:54 UTC, aranion commented on packages/client/src/components/Star/index.ts
> +export {default} from './Star';
Файл `packages/client/src/components/index.ts` подразумевал экспорт всех компонент из одного места:
 `./components`. 
Тoeсть все необходимые компоненты импортируются из одного импорта: 
`import {Loader, Button, Input} from '../component'` 
вместо
`import Loader  from '../component/Loader'
import Button  from '../component/Button'
import Input from '../component/Input'
`

2022-10-30 17:04 UTC, aranion commented on packages/client/src/pages/SignIn/SignIn.tsx
> +import Button from '../../components/Button';
Наверное лучше назвать файл SignIn.tsx как index.tsx. (Папка SignIn представляет собой отдельный компонент)
Если делать экспорт компонента при наименовании файла 'SignIn.tsx':
`import SignIn from '../component/SignIn/SignIn`
экспорт если именовать файл, как 'index.tsx':
`import SignIn from '../component/SignIn`

2022-10-30 17:13 UTC, aranion commented on packages/client/src/pages/SignUp/SignUp.tsx
> +      <Star top='3%' left='10%' />
Звезды - хорошо, но выглядит громоздко :)
Думаю стоит рассмотреть возможность автоматического создания подобных <Star>.
Например вынести top и left в отдельную переменную и потом пробегаться по ней.
`const configStar = [ {top: '3%', left: '10%'}, {top: '52%', left: '19%', {top: '4%', left: '76%'}} ];`
в месте вставки компонентов: 
`{ configStar.map((item, idx) => <Star key={idx} top={item.top} left={item.left} />) }`

2022-10-30 19:11 UTC, elaineir requested changes
В целом хорошо, есть комментарии, которые стоит поправить.
Выделила также ошибки по БЭМ, раз мы используем эту методологию.

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/components/Button/Button.tsx
> +export class Button extends PureComponent<ButtonProps> {
Давайте использовать функциональные компоненты. С 16 версии Реакта классовые уходят в историю и сейчас уже не используются в новых проектах (кроме одного специального). Как говорил мой прошлый наставник: "Если вы начали писать на классовых компонентах, лучше Астанавитесь и пишите на функциональных" :)

Дополнительно про мемоизацию: при использовании пропа `children` мемоизация смысла не имеет, т.к. реакт сравнивает поверхностно, и если в пропе будет нода, то реакт просто не сможет её сравнить с предыдущей. В этом плане стоит использовать другой проп, если подразумевается только текст, то типизировать его строкой.

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/components/Button/Button.tsx
> +    onClick?: (...args: any) => void;
Вместо `any` лучше использовать `unknown[]`. Точный тип данных неизвестен, но это массив аргументов неизвестного типа.
Тогда и линтер не будет ругаться.
А лучше дополнительно использовать уже предопределенные типы для кнопки в `ButtonHTMLAttributes`, `onClick` там тоже должен быть.

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/components/Button/Button.tsx
> +    render() {
Табуляция в разных ts-файлах разная: где-то 2 пробела, где-то 4. Лучше привести все к одному виду.

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/components/Star/Star.css
> +.star__big {
Если придерживаться БЭМ, то в таких случаях вместо элементов используются модификаторы, в данном кейсе -- ключ-значение
https://ru.bem.info/methodology/quick-start/#%D0%BA%D0%BB%D1%8E%D1%87-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5

`star_size_big`, `star_size_small`,  `star_pos_relative`

При конкатенации классов в коде ниже сейчас возникает ошибка по БЭМ, когда элемент используется без своего блока: `star star__big` <- ошибка, в разметке элемент не вложен в свой блок (блок и элемент должны быть разными html-элементами)

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/components/Button/Button.tsx
> +};
Лучше ещё добавить `& ButtonHTMLAttributes<HTMLButtonElement>`, чтобы у кнопки были доступны все стандартные атрибуты.

```suggestion
} & ButtonHTMLAttributes<HTMLButtonElement>;
```

А в разметке сделать так: `<button {...props} className={classNames}>`

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/components/Input/Input.tsx
> +};
Тут тоже стоит добавить типизированные стандартные атрибуты для поля ввода `InputHTMLAttributes<HTMLInputElement>`

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/components/Star/Star.tsx
> +        const classNames = classnames('star', 'star__' + size, this.props.className);
Вместо конкатенации лучше использовать шаблонную строку: они легче читаются и, если верить некоторым бенчмаркам, исполняются быстрее.

```suggestion
        const classNames = classnames('star', `star_size_${size}`, className);
```

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/components/Button/Button.css
> +    font-family: 'Audiowide';
Для текстовых элементов необходимо указать дополнительный безопасный веб-шрифт (хотя бы один из системных) и тип засечек на случай, если `Audiowide` не прогрузится.

Здесь и в других файлах, это важно.
И лучше вынести в css-переменную `font` или `mainFont` и использовать уже её, чтобы в случае смены шрифта не переписывать все файлы.

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/index.css
> +    .mobile__hide {
Здесь тоже получился класс не по БЭМ: элемент используется без блока. Для этого нужно использовать блок + булевый модификатор `mobile mobile_hidden`, и в модификаторе указать на изменение свойства `display`

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/main.tsx
> +import './vendor/normalize.css';
Все глобальные стили лучше собирать в корневом `index.css`, чтобы в ts не было нагромождения импортов

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/pages/SignIn/SignIn.css
> +.input.login__input {
Не обязательно делать составной селектор, `login__input` уже передается в компонент как миксин.
Также это затруднит поддержку кода, так как этот класс становится завязан на класс `input`, и если класс дочернего компонента поменяет название, то придется править его во всех подобных селекторах

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/pages/SignIn/SignIn.css
> +.button.login__button__signin {
Тоже лучше использовать простой селектор.
Также здесь ошибка по БЭМ: не может быть элемента элемента. Схема валидного элемента по БЭМ: `блок__элемент`. Можно назвать класс `login__signin-button`

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/pages/SignIn/SignIn.css
> +.button.login__button__signup {
Аналогичная ошибка по БЭМ: не может быть элемента элемента.  Можно назвать класс `login__signup-button`

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/pages/SignIn/SignIn.tsx
> +      <Star size='small' className='star__relative' />
Назначение класса `star__relative` нужно инкапсулировать в компоненте, т.к. это его внутрянка. Можно задать проп, который будет его 'активировать'. Если класс поменяется, то придется менять его во всех компонентах, которые его используют.

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/pages/SignUp/SignUp.css
> +.registration {
Здесь почти все стили дублируют `login`.
Стоит создать универсальный компонент, который можно будет переиспользовать на обеих страницах. Например, `AuthForm`. Для стилизованных детей можно использовать такой паттерн как `Compound components` и вставлять их как  `children`, но с привязкой к `AuthForm`
Пример:
```
<AuthForm onSubmit={someFunc}>
  <AuthForm.Input onChange={someFunction} />
</AuthForm>
```
Подробнее про паттерн можно почитать тут: https://habr.com/en/company/alfa/blog/647013/

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/pages/SignIn/SignIn.tsx
> +      <Input placeholder='Password' className='login__input' />
Для полей ввода нужно указать корректные типы. Для пароля стоит использовать `type='password'`, чтобы вводимый текст отображался точками и данные нельзя было скопировать в буфер обмена

Остальные типы: https://doka.guide/html/input/#type

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/components/Star/Star.tsx
> +    top?: string;
Для координат стоит задать значения по умолчанию, если они не обязательные

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/pages/SignIn/SignIn.tsx
> +      <Button className='login__button__signin' onClick={handleSignIn}>Sign In</Button>
Формы сабмитятся через событие `submit`, которое слушается на форме, не кнопке: https://learn.javascript.ru/forms-submit

Обработчик нужно повесить на форму через `onSubmit`

2022-10-30 19:11 UTC, elaineir commented on packages/client/src/pages/SignUp/SignUp.tsx
> +      <Button className='registration__button__signin' onClick={handleSignUp}>Sign Up</Button>
Обработчик нужно повесить на форму через `onSubmit`

2022-10-30 20:21 UTC, aranion commented on packages/client/src/components/Button/Button.css
> +    font-family: 'Audiowide';
Возможно стоит даже вынести `font-family` на верхний уровень например элемент div с id=Root? Если мы используем один шрифт по всему проекту имеет ли смысл прописывать его в каждом классе?

2022-10-31 07:22 UTC, elaineir commented on packages/client/src/components/Button/Button.css
> +    font-family: 'Audiowide';
Да, можно использовать на верхнем уровне, но не все элементы наследуют `font-family`, например, input. Для них все равно нужно будет прописывать отдельно.

2022-10-31 08:13 UTC, aranion commented on packages/client/src/router/index.tsx
> +          <Route index element={<SignInPage />} />
Основная страница сайта  "/game", если пользователь не авторизован его перенаправляет на "/sign-in". 
В таком виде `<Route index element={<SignInPage />} />` получается, что мы при любом входе(есть авторизация или нет, попадает на страницу авторизации).
В случае `<Route index element={withPrivateRoute(<GamePage />)} />` при входе на страницу "/" проверяется авторизация, если она `true` переходим на "/game" иначе реконенктит на "/sign-in"
Если нужен обход авторизации, можно в `withPrivateRoute` временно установить флаг `true`

2022-11-02 18:19 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/SignIn/SignIn.tsx
> +import Button from '../../components/Button';
@aranion Не, тут всё ок, здесь есть index.ts, в котором стоит экспорт, поэтому 
`import SignIn from '../pages/SignIn`
спокойно работает

Напиши, если я вдруг тебя неправильно понял!

2022-11-02 18:25 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/SignIn/SignIn.css
> +.input.login__input {
@elaineir Я знаю, что это не очень удобно, но я сделал это, потому что возникла проблема:
На vercel почему-то классы из Input.css подтягивались после этих, поэтому все значения, заданные тут, перебивались теми, что я задал изначально ему в Input.css

Просто говоря: я задавал здесь новую ширину и длину инпуту, но ничего не работало, потому что дефолтные width и height, которые я задал для инпута в Input.css, шли в стилях позже, и делали оверрайд.

Я вспомнил каскадность и поставил тут селектор input, чтобы повысить приоритет этого селектора.

Подскажи пожалуйста, у тебя нет идей, как по-другому можно было бы поправить проблему?

2022-11-03 07:54 UTC, aranion commented on packages/client/src/pages/SignIn/SignIn.tsx
> +import Button from '../../components/Button';
Да, вижу, можно оставить и так. 
Тут получается мы создаем файл index.ts котррый дублирует экспорт signIn.tsx, преимцщества тут врядли какое-то будет, но создается лишний файл. 
Папка SignIn подразумевае собой отдельный компонент(страницу) и экспортировать от туда еще, что либо кроме SignIn.tsx не стоит, поэтом думаю имеет смысл переименовать SignIn.tsx в index.tsx остаить только его.

2022-11-03 08:00 UTC, elaineir commented on packages/client/src/pages/SignIn/SignIn.css
> +.input.login__input {
Да, странно, vite почему-то ставит стили потомков ниже, чем родительские, и это подтвержденный issue
https://github.com/vitejs/vite/issues/3924

И похоже, что это проблема только с лениво загруженными компонентами.
Сейчас у input нет ширины и высоты и ничего не перебивается. Но на такие случаи, думаю, можно слегка отойти от БЭМ и использовать специфичность, но по тегам, раз мы уверены, что это стиль именно для инпута. То есть вместо класса использовать `input.login__input`

2022-11-03 10:18 UTC, aranion commented on lerna-debug.log
> +0 silly argv {
думаю этот фай не нужен в репо, надо будет добавить в исключения .gitignore

2022-11-03 10:20 UTC, aranion commented on lerna-debug.log
> +3 error > 14 | <<<<<<< HEAD
ну раз уж файлик тут :) тут есть проблема в `packages\client\package.json` надо удалить строку с ` | <<<<<<< HEAD`

2022-11-03 10:24 UTC, aranion commented on packages/client/index.html
> +    <link rel="preconnect" href="https://fonts.googleapis.com" />
Может быть лучше в index.css подключить шрифт?
`@import url('https://fonts.googleapis.com/css2?family=Audiowide&display=swap');`

одна строка против трех )

2022-11-03 10:28 UTC, aranion commented on packages/client/src/components/Button/Button.tsx
>  import './Button.css';
Не слишком много чести для `.ccs` чтобы его с большой буквы обзывать? :)

2022-11-03 11:11 UTC, elaineir commented on packages/client/src/components/Button/Button.tsx
>  import './Button.css';
Не стоит недооценивать css :)

![kr77pTq](https://user-images.githubusercontent.com/75016726/199705946-d2cf24dc-89b1-46d5-abd4-f16290b71c90.png)

2022-11-03 14:28 UTC, HereHaveTheseFlowers commented on lerna-debug.log
> +3 error > 14 | <<<<<<< HEAD
Дааа, я это сразу пофиксил, просто в логах осталось

2022-11-03 14:28 UTC, HereHaveTheseFlowers commented on lerna-debug.log
> +0 silly argv {
Оке, я добавлю

2022-11-03 14:28 UTC, HereHaveTheseFlowers commented on packages/client/index.html
> +    <link rel="preconnect" href="https://fonts.googleapis.com" />
Супер, так и сделаю)

2022-11-03 14:30 UTC, HereHaveTheseFlowers commented on packages/client/src/components/Button/Button.tsx
>  import './Button.css';
@aranion Если честно я привык компоненты обзывать с большой буквы, а css по названию компонента же

2022-11-03 15:31 UTC, HereHaveTheseFlowers commented on packages/client/src/components/Star/index.ts
> +export {default} from './Star';
Вау, это очень удобно! А я всё задавался вопросом, почему ты сделал именно так)

2022-11-03 15:35 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/SignIn/SignIn.tsx
> +import Button from '../../components/Button';
@aranion Тогда SignIn.css и ему подобные лучше называть `styles.css`?

2022-11-03 16:17 UTC, HereHaveTheseFlowers commented on packages/client/src/pages/SignIn/SignIn.css
> +.input.login__input {
@elaineir Хмм, да, видимо, это в ближайшее время не пофиксят. Я правильно понимаю, что оставляем `input.login__input` покачто?

2022-11-03 16:20 UTC, elaineir commented on packages/client/src/pages/SignIn/SignIn.css
> +.input.login__input {
Да, оставим `input.login__input`

2022-11-03 16:31 UTC, HereHaveTheseFlowers commented on packages/client/src/components/Star/Star.tsx
> +    top?: string;
@elaineir тогда сломается использование star_position_relative

2022-11-03 17:46 UTC, HereHaveTheseFlowers commented
@aranion  @elaineir  Большое спасибо вам двоим за проделанную работу над моим ПР-ом, было интересно узнавать новые для меня штуки. Мне явно стоит подтянуть БЭМ, ну и, естественно, Реакт.

Я постарался исправить всё, о чем вы говорили, оставил анрезолвд только несколько комментариев.

Можете смотреть, и, если всё ок, апрувать

2022-11-03 17:57 UTC, HereHaveTheseFlowers commented
Что-то очень странное:
На локалке у меня всё запускается и работает совершенно нормально, а на деплое в vercel здесь вылетает какая то странная ошибка:
```index.39e0863d.js:32 TypeError: Cannot destructure property 'store' of 't(...)' as it is null.```

2022-11-03 17:59 UTC, aranion commented on packages/client/src/pages/SignIn/SignIn.tsx
> +import Button from '../../components/Button';
имхо - думаю да, на код и работу это вряд ли повлияет, да и искать стили все равно идем сразу в компонент, без поиска по названию.

2022-11-03 18:03 UTC, aranion commented on packages/client/src/components/Button/Button.tsx
>  import './Button.css';
Не, ну компоненты с большой буквы это да)

2022-11-03 18:22 UTC, aranion commented on packages/client/src/router/index.tsx
> +import { Loader } from '../components/Loader';
странно, но автоматом должен импортировать из `import { Loader } from '../components'` без дополнительного указания `/Loader`, а то вся суть теряется такого импорта

2022-11-04 09:19 UTC, HereHaveTheseFlowers commented
Проблема была в `yarn.lock`!
Теперь всё работает нормально.
@practicum-maxim-zyryanov апрув плиз (хотя сегодня в раше вроде выходной, так что можешь не торопиться

2022-11-05 07:39 UTC, practicum-maxim-zyryanov approved these changes

2022-11-05 14:38 UTC, HereHaveTheseFlowers commented
@elaineir Привет. От тебя апрув?

2022-11-05 17:53 UTC, elaineir approved these changes
Да, делаю апрув, хотя в коде есть что улучшить. Оставила комментарии.

2022-11-05 17:53 UTC, elaineir commented on packages/client/src/components/index.ts
> +export * from './AuthForm';
Тут возникла циклическая зависимость: форма импортирует этот файл и сама экспортируется в этот файл. Это распространенная ошибка, возникающая при реэкспорте пачки компонентов. В форму лучше импортировать компоненты отдельно или убрать её из экспорта.

2022-11-05 17:53 UTC, elaineir commented on packages/client/src/pages/SignIn/index.tsx
> +  const navigateSignUp = useCallback(
Не помню в прошлом коде, возможно просмотрела.
Кнопка не мемоизированная, так что оборачивать в `useCallback` смысла нет. Кнопка все равно будет перерисовываться при каждом триггере рендера, а коллбек создаваться в `useCallback`. Сейчас мемоизация обработчика занимает лишнюю память.

Ну и саму кнопку нет смысла мемоизировать из-за пропа `children`

2022-11-05 17:53 UTC, elaineir commented on packages/client/src/pages/SignUp/index.tsx
> +  const navigateSignIn = useCallback(
Здесь тоже `useCallback` используется без особой необходимости

2022-11-05 17:53 UTC, elaineir commented on packages/client/src/pages/SignUp/styles.css
> +.registration {
В файле по прежнему осталось много дублирующихся стилей, стоило бы их объединить

2022-11-05 18:01 UTC, elaineir commented on packages/client/src/components/AuthForm/styles.css
> +  .login__signin-button {
И здесь ещё классы, не относящиеся к `authform` почему-то

2022-11-05 21:42 UTC, merged