feature/AND-78 Приватный роутер через Redux
aranion/game_andromeda pull request #8
Opened 2022-10-30 18:18 UTC by aranion

### Какую задачу решаем
Подготовил Redux. Настроил приватный роутер в зависимости, от авторизации пользователя. В компонентах SignIn и SignUp добавлены общие данные и кнопки, для проверки работы API и приватного роутера. При реализации страницы входа и выхода, в переменную params необходимо передать данные из формы и удалить данные указанные в коде.

2022-10-31 08:57 UTC, elaineir requested changes
В целом отлично, стоит также внедрить селекторы и вынести логику авторизации в хук, чтобы в компонентах использовать только готовые обработчики.

Сейчас ещё есть баг, когда авторизовался и перешел на защищенную страницу, а при рефреше не оставляет на текущей и перебрасывается обратно на логин.
Шаги:
- авторизоваться
- перейти на страницу профиля
- нажать F5

Ожидаемый результат: остаться на странице профиля
Получаемый результат: редирект на страницу логина

Здесь надо дождаться ответа сервера перед тем, как отрисовывать приложение.

Ещё в некоторых файлах код не отформатирован, нет точек с запятой :)
Стоит прогнать командой `format`, чтобы все было единообразно

2022-10-31 08:57 UTC, elaineir commented on packages/client/src/pages/SignIn/index.tsx
> +  const { isAuth } = useTypeSelector(state => state.auth);
Чтобы не мапить каждый раз хранилище, стоит использовать простые селекторы 
https://habr.com/ru/post/564004/

Итоговый код будет примерно таким:
`const { isAuth } = useTypeSelector(authSelector);`
Файл с селекторами можно расположить на уровне подраздела хранилища, там же, где `slice`, `api`

2022-10-31 08:57 UTC, elaineir commented on packages/client/src/pages/SignIn/index.tsx
> +  const handleCheckIsAuth = () => {
Возможно все эти действия стоит упаковать в хук `useAuth`, чтобы в дальнейшем использовать уже готовые обработчики в компонентах.

2022-10-31 08:57 UTC, elaineir commented on packages/client/src/pages/SignIn/index.tsx
> +      setIsAuth(res.isSuccess);
Здесь можно деструктурировать
```suggestion
    fetchAuthUser(null).then(({ isSuccess }) => {
      setIsAuth(isSuccess);
```

2022-10-31 08:57 UTC, elaineir commented on packages/client/src/pages/SignIn/index.tsx
> +          fetchUserData(params).then(res => {
```suggestion
          fetchUserData(params).then(user => {
```
Хорошей практикой считается сразу указывать, какие именно данные находятся в `res`, чтобы не выводить это из кода ниже. В данном случае это `user`

2022-10-31 08:57 UTC, elaineir commented on packages/client/src/pages/SignUp/index.tsx
> +  const handleSignUp = () => {
Тоже стоит вынести в хук `useAuth`

2022-10-31 08:57 UTC, elaineir commented on packages/client/src/store/auth/api.ts
> +  useCheckAuthUserQuery,
Метод нигде не используется. Если это не заготовка под будущую логику, то его стоит удалить

2022-10-31 09:01 UTC, elaineir commented
Забыла ещё написать, что точек с запятой в конце нет))
Надо бы отформатировать код, чтобы все было единообразно.

2022-10-31 18:03 UTC, aranion commented on packages/client/src/pages/SignIn/index.tsx
> +  const { isAuth } = useTypeSelector(state => state.auth);
Спасибо за статью, раньше думал, что это только для удобства делается!

2022-10-31 21:50 UTC, aranion commented on packages/client/src/pages/SignIn/index.tsx
> +  const handleCheckIsAuth = () => {
Добавил

2022-10-31 21:51 UTC, aranion commented on packages/client/src/pages/SignIn/index.tsx
> +      setIsAuth(res.isSuccess);
+

2022-10-31 22:01 UTC, aranion commented on packages/client/src/store/auth/api.ts
> +  useCheckAuthUserQuery,
да, для будущих на компонент

2022-11-01 09:35 UTC, elaineir requested changes

2022-11-01 09:35 UTC, elaineir commented on packages/client/src/components/NoAccess/index.tsx
> +export function NoAccess() {
ИМХО, конечно, но "Проверка доступа" навевает о всяких банках с 100500 степенями защиты :)

Для игры можно просто лоадер поставить, пока идет проверка, так будет дружелюбнее

2022-11-01 09:35 UTC, elaineir commented on packages/client/src/hooks/usuAuth.ts
> +import { RouterList } from './../router/routerList';
```suggestion
import { RouterList } from '../router/routerList';
```

2022-11-01 09:35 UTC, elaineir commented on packages/client/src/hooks/usuAuth.ts
> +        setIsAuth(isSuccess);
```suggestion
      .then(({ isSuccess }) => setIsAuth(isSuccess))
```
Лучше деструктурировать прямо в параметре. Иначе смысла немного в 32 строке.

2022-11-01 09:35 UTC, elaineir commented on packages/client/src/hooks/usuAuth.ts
> +      });
Пропустила в прошлом ревью: все асинхронные процедуры нужно дополнять блоком `catch`, чтобы обработать возможные исключения

2022-11-01 09:35 UTC, elaineir commented on packages/client/src/hooks/usuAuth.ts
> +      });
Здесь тоже нужен `catch`

2022-11-01 09:35 UTC, elaineir commented on packages/client/src/hooks/usuAuth.ts
> +      });
Здесь тоже нужен `catch`

2022-11-01 09:35 UTC, elaineir commented on packages/client/src/hooks/usuAuth.ts
> +2;
Случайная опечатка
В названии файла тоже есть опечатка: usuAuth -> useAuth

2022-11-01 09:35 UTC, elaineir commented on packages/client/src/pages/SignIn/index.tsx
> +      <button onClick={handleCheckIsAuth}>Проверить авторизацию</button>
```suggestion
      <button onClick={checkIsAuth}>Проверить авторизацию</button>
```
Нужно сразу передать, не создавая доп. функцию. У `checkIsAuth` нет аргументов

2022-11-01 09:35 UTC, elaineir commented on packages/client/src/pages/SignIn/index.tsx
> +      <button onClick={handleLogout}>Выход</button>
```suggestion
      <button onClick={logout}>Выход</button>
```
Здесь тоже не нужна доп. функция

2022-11-01 11:53 UTC, aranion commented on packages/client/src/components/NoAccess/index.tsx
> +export function NoAccess() {
:) Заменю

2022-11-01 11:58 UTC, aranion commented on packages/client/src/hooks/usuAuth.ts
> +      });
ага

2022-11-01 11:59 UTC, aranion commented on packages/client/src/hooks/usuAuth.ts
> +2;
хмм, исправлю

2022-11-01 12:02 UTC, aranion commented on packages/client/src/pages/SignIn/index.tsx
> +      <button onClick={handleCheckIsAuth}>Проверить авторизацию</button>
Если потребуестя дополнительная функциональности кнопки придется выносить в новую функцию. Да и эти кнопки тут только для проверки работы, они будут заменены на другие. Пока пусть так будет.

2022-11-01 13:34 UTC, elaineir approved these changes

2022-11-01 15:41 UTC, practicum-maxim-zyryanov approved these changes

2022-11-01 19:03 UTC, merged